### ISSUE TITLE
Working with foreman.

### ISSUE THREAD

**Issue by eloyesp** [bkeepers/dotenv#114]
The recommendation is to commit the `.env` file with the development only values, so development machines can get running faster, and I like the idea.

But, if [Foreman](https://github.com/ddollar/foreman) is used to run in production (like heroku does) then the environment is set there by this file (as it uses dotenv internally) and it seems to override the current environment.

To solve this, [Heroku recommends](https://devcenter.heroku.com/articles/procfile#setting-local-environment-variables) **not** to commit the `.env` file, but I don't like that, as I like that feature, is there a way to solve it?

**Comment by artemave** [comment]
If only it was possible to pass a list of files to `Dotenv::Railtie.load` - much like it is possible to do so for `Dotenv.load`
