### ISSUE TITLE
Empty ENV vars get turned into empty string, which is truthy in Ruby.

### ISSUE THREAD

**Issue by cmaitchison** [bkeepers/dotenv#115]
If I have this in my .env file

```
FEATURE_A_ENABLED=true
FEATURE_B_ENABLED=
```

The first line works as expected, but the second also behaves as true.

```
if ENV['FEATURE_B_ENABLED']
  do_some_stuff
end
```

In this case, `do_some_stuff` will be called. My natural expectation is that it wouldn't be.

dotenv sets ENV['FEATURE_B_ENABLED'] to `""`, which is truthy.

I would expect that ENV['FEATURE_B_ENABLED'] would be `nil`.

**Comment by Nuru** [comment]
@bkeepers Unfortunately, commenting out a variable to make it `nil` is not compatible with the override system you have implemented. If we have a default value in `.env` that I want to override in `.env.local`, I cannot override it to set it to nil. 

We want it to be `nil` so we can use standard idioms like
```
CONSTANT = ENV['CONSTANT'] || 'default'

send_mail unless ENV['INHIBIT_MAIL']
```
and so on.

**Comment by lflucasferreira** [comment]
Heys guys! 

I am facing this issue right now and I do not know what one of you did to solve this problem. Have anyone a solution for this case?

OS: Windows 10
Ruby Version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

**Comment by xanderman** [comment]
My current solution is to use `.presence` to turn `""` into `nil`. It leaks the problem in to the code, but only a little. I only use it for variables that I need to be able to override like this. The above examples become:

```
CONSTATN = ENV['CONSTANT'].presence || 'default'

# this works
send_mail unless ENV['INHIBIT_MAIL'].presence
# but I actually prefer this, because INHIBIT_MAIL=false shouldn't inhibit mail
send_mail unless ENV.fetch('INHIBIT_MAIL', 'false') == 'true'
```
