### ISSUE TITLE
Sidekiq not loading .env

### ISSUE THREAD

**Issue by axsuul** [bkeepers/dotenv#134]
Rails seems to be loading `.env`  fine but Sidekiq in production doesn't seem to be. However, if I create an initializer with

``` ruby
Dotenv.load Rails.root.join('.env')
```

it picks it up fine.  Note that in production, the sidekiq executable is contained within `bin/` so it could be related to https://github.com/bkeepers/dotenv/issues/82

**Comment by PedroSena** [comment]
I'm using dotenv 1.0.2 and having the same issue, even with the initializer

**Comment by bkeepers** [comment]
@PedroSena dotenv 2.0.0 is out now. Can you give that a try and see if you still experience issues?

**Comment by PedroSena** [comment]
Same issue, @bkeepers

**Comment by bkeepers** [comment]
I'm not familiar with how Sidekiq boostraps, so I'd appreciate help looking into the issue. Reopening this issue now.

**Comment by parkr** [comment]
I'd recommend setting the env vars when starting up the sidekiq master, rather than relying on the sidekiq process(es) to read in the .env file. It's really not meant for production (partly because of weird edge cases like this).

**Comment by paul-ylz** [comment]
I had used Mike Perham's upstart scripts for loading Sidekiq in production and found that I had to add a line to export the env variables before sidekiq loads.

**Comment by PedroSena** [comment]
Leaving dotenv just for dev/test and loading the variables on /etc/environment for production solved the issue. Thanks for the help

**Comment by hbin** [comment]
@PedroSena I don't think `/etc/environment` is a good place to put `project-related` environment variables.

**Comment by assimovt** [comment]
I am having a similar issue, using Runit with Sidekiq and currently manually sourcing every .env file.

**Comment by mathieugagne** [comment]
Jumping a little late on this but hope it can help.
@assimovt do you `cd` to your application folder in your Runit config before starting sidekiq?

Here's my capistrano template for a sidekiq runit config:
```bash
#!/bin/bash --login

PATH=<%= fetch(:rbenv_path) %>/shims:<%= fetch(:rbenv_path) %>/bin:/usr/local/bin:/usr/bin:/bin
exec 2>&1
cd <%= current_path %> && exec bundle exec sidekiq -e <%= fetch(:rails_env) %>
```

Works well for me.

**Comment by Sathors** [comment]
Nobody has any news on that?

I am currently having the same problem, using dotenv and capistrano-sidekiq.

**Comment by Sathors** [comment]
Actually, it finally worked, with capistrano-sidekiq.

**Comment by wflanagan** [comment]
This is still the case.

**Comment by joschl** [comment]
put `require 'dotenv/load'` right after `require 'bundler/setup'` into bin/sidekiq
