### ISSUE TITLE
undefined method 'join' for nil:NilClass - Rails

### ISSUE THREAD

**Issue by chrisjbatts** [bkeepers/dotenv#155]
Followed the instructions on the readme and found an error at the point where the config/application.rb instructs the following: 

```Ruby
# config/application.rb
Bundler.require(*Rails.groups)

Dotenv::Railtie.load
```
Error: 
```
gems/dotenv-rails-1.0.2/lib/dotenv/rails.rb:17:in `load': undefined method `join' for nil:NilClass (NoMethodError)
```

Rails console and rspec failed to run with the error.

Patched the error by entirely removing:
```
Dotenv::Railtie.load
```

and then adding the following inside the rails application module/class:

```Ruby
module RailsAppName
  class Application < Rails::Application
    Dotenv.load Rails.root.join('.env')
  end
end 
```

Is this a known bug?

**Comment by j-mcnally** [comment]
My work around for now is

Dotenv.load(File.expand_path("../../.env.#{Rails.env}", __FILE__))

**Comment by chrisjbatts** [comment]
cheers, will give it a try on the next project - probably about 2 weeks or so

**Comment by krishnasrihari** [comment]
Thanks,  mcnally code works for me.

Dotenv.load(File.expand_path("../../.env.#{Rails.env}", __FILE__))
