### ISSUE TITLE
jRuby java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Mehonoshin** [bkeepers/dotenv#168]
Hi folks!

I'm having an issue, when trying to run app with dotenv via jRuby.
I'm using 1.7.18 and Rails 4.2

```
~/p/rnd(master ✗) RBENV_VERSION=jruby-1.7.18 rspec
LoadError: load error: /Users/smekhonoshin/p/rnd/config/application -- java.lang.ArrayIndexOutOfBoundsException: 0
          require at org/jruby/RubyKernel.java:1071
           (root) at /Users/smekhonoshin/p/rnd/config/environment.rb:2
          require at org/jruby/RubyKernel.java:1071
           (root) at /Users/smekhonoshin/p/rnd/spec/rails_helper.rb:1
          require at org/jruby/RubyKernel.java:1071
           (root) at /Users/smekhonoshin/p/rnd/spec/rails_helper.rb:3
             load at org/jruby/RubyKernel.java:1087
           (root) at /Users/smekhonoshin/p/rnd/spec/clients/api/dropbox/directory_spec.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/smekhonoshin/p/rnd/spec/clients/api/dropbox/directory_spec.rb:1
           (root) at /Users/smekhonoshin/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1
  load_spec_files at /Users/smekhonoshin/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
  load_spec_files at /Users/smekhonoshin/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
            setup at /Users/smekhonoshin/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96
              run at /Users/smekhonoshin/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84
             load at org/jruby/RubyKernel.java:1087
           (root) at /Users/smekhonoshin/.rbenv/versions/jruby-1.7.18/bin/rspec:23
```

This trace is not obvious, but if I remove dotenv from Gemfile, then app is loaded well.

I'm not sure, maybe it is a jRuby issue, maybe dotenv.

Probably anybody faced with such problem? Search doesn't give any usefull information.

UPD: it seems to be an issue with loading spring. Digging deeper

**Comment by bkeepers** [comment]
Thanks for the report! Keep us updated with what you find out.

**Comment by bkeepers** [comment]
Did you find anything else out?

I'm going to close this since we don't officially support jruby. I would gladly accept a pull request that adds jruby to the travis config and makes sure everything works, but it won't be a priority for me.

**Comment by Elyasin** [comment]
@Mehonoshin I am porting an application from MRI to JRuby and ran into the same error message that you posted. Did you find a solution or a workaround?

**Comment by Mehonoshin** [comment]
@Elyasin actually it was problem with Spring preloader incompatibility.
I had to disable it in my app.

**Comment by fullstackadept** [comment]
Interesting, while testing an OS upgrade (Ubuntu 15.04), I just got this same error with an app that used to build with JRuby 1.7.18 and Rails 4.1 (also using dotenv). Disabling the Spring preloader still failed for me, but updating jruby and jruby-jars to 1.7.21 seems to have fixed it.

**Comment by rpazyaquian** [comment]
Updating jruby from 1.7.19 to 1.7.21 also fixed the problem for me.
