### ISSUE TITLE
Only unescapes env-vars if their value is quoted and differs from regular env vars behavior

### ISSUE THREAD

**Issue by davidpelaez** [bkeepers/dotenv#170]
The lines in https://github.com/bkeepers/dotenv/blob/1b656f029e4d4d12fb925127139c367e8d3f07a5/lib/dotenv/parser.rb#L65-L79 show that when the env var value isn't quoted unescaping isn't performed. This differs from the value that ruby would have when reading from ENV. 

Hence, the same value results in different behavior in bash and dotenv. I see this as a potential security feature, not a bug, but I'm not sure if this is ideal since it can break apps. This was the case for us for an app being started through foreman in dokku-alt the related issue can be found here https://github.com/dokku-alt/dokku-alt/issues/204

Maybe some clarification on your position regarding this in order to understand where to tackle the situation would be helpful. Thanks!

**Comment by bkeepers** [comment]
I think dotenv should mimic bash behavior wherever possible, so a pull request to make the escaping match would be a appreciated.

**Comment by davidpelaez** [comment]
Yes sir, give me a moment and I'll send it over today.

**Comment by ayufan** [comment]
Heh. What should I do with it? :)

**Comment by davidpelaez** [comment]
@ayufan this would be included in foreman, and then in the container's using foreman to start execution, e.g: in a ruby app. Regarding dokku-alt, a fix could also be provided without waiting for all the involved parts in dotenv/foreman/buildstep to make updates if you accept this small PR https://github.com/dokku-alt/dokku-alt/pull/205 Basically, this is can (and ideally) should be solved from both sides.

**Comment by ayufan** [comment]
Maybe it would be better to provide own compilation of foreman instead? We have own buildstep: https://github.com/dokku-alt/progrium-buildstep-dockerfiles
