### ISSUE TITLE
dotenv-rails not loaded early enough

### ISSUE THREAD

**Issue by mathieujobin** [bkeepers/dotenv#178]
I am having an issue similar to this other one https://github.com/bkeepers/dotenv/issues/19

using dotenv 2.0.0 in a Rails 4.1.9 application

the problem comes from the fact I tried to use a environment variable early in my Rails Engine initializer.

the engine is loaded through a gem.

I tried moving the `gem 'dotenv-rails'` to the engine gemspec
I tried doing a `require 'dotenv-rails'` above my usage, but no luck,...

any idea what else I could be doing ?
thanks

**Comment by mathieujobin** [comment]
I just found one solution.

on top of my `lib/engine.rb` I do 

```ruby
require 'dotenv-rails'
Dotenv.load('.env')
```

unless you can suggest a better solution, you can close my issue.

thanks

CC: @cedricboulanger

**Comment by bkeepers** [comment]
This is one of the inherent problems with dotenv. If you need it to be initialized earlier, I recommend doing it manually like you currently are doing. Right after the `Bundler.require` call in `config/application.rb` would be ideal, but I don't know if that will be early enough for what you need.

:hatched_chick: :hatching_chick:
