### ISSUE TITLE
variables not overridden since .env loaded after .env.{environment} and .env.local

### ISSUE THREAD

**Issue by nakhli** [bkeepers/dotenv#179]
Files `.env.local` and `.env.#{Rails.env}` are loaded before the `.env` file. The variables defined in `.env` are therefore not overriden by the more specific files `.env.local` and `.env.#{Rails.env}`

See [code](https://github.com/bkeepers/dotenv/blob/master/lib%2Fdotenv%2Frails.rb#L27-L30)
```ruby
def load
  Dotenv.load(
    root.join(".env.local"),
    root.join(".env.#{Rails.env}"),
    root.join(".env")
  )
end
```

Is this done by "design"? could we change it so more specific files are loaded last to correctly override the `.env` values?

**Comment by bkeepers** [comment]
With `load` the first value set actually wins. So values from `.env.local` should get set first. Is that not the behavior you are seeing?

**Comment by nakhli** [comment]
Not sure what happened. Now I am seeing the correct behavior. thank you for your answer!

**Comment by PhilT** [comment]
I'm actually seeing the reverse of this. Whatever is set last wins.

    Dotenv.load(".env", ".env.local") => # value in .env.local is returned
    Dotenv.load(".env.local",".env") => # value in .env is returned

**Comment by bkeepers** [comment]
Can show more code samples of how you're seeing this?  Here's what I just did:

$  rails new first; cd first
$ echo 'gem "dotenv-rails"' >> Gemfile; bundle                              
…
Installing dotenv 2.0.1
Installing dotenv-rails 2.0.1
Your bundle is complete!

$ echo "WHO_WINS=.env" > .env
$ echo "WHO_WINS=.env.local" > .env.local
$ rails runner 'puts ENV["WHO_WINS"]'
.env.local
```

And just to make sure it's not Rails interfering, here's just dotenv straight up:

```
$ ruby -r dotenv -e 'Dotenv.load(".env", ".env.local"); puts ENV["WHO_WINS"]'
.env
$ ruby -r dotenv -e 'Dotenv.load(".env.local", ".env"); puts ENV["WHO_WINS"]'
.env.local
```

**Comment by PhilT** [comment]
My mistake, just checked again and it's fine. I must have been looking at the return value from `Dotenv.load`

**Comment by idrozd** [comment]
To reload your env in default order in runtime to imitate Railtie, you will have to manually call:
```ruby
Dotenv.overload('.env', '.env.development', '.env.local')
```

For all those who are banging their heads against the wall, railtie works as advertised because of **||=** in **Dotenv::Environment**:
```ruby
# https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/environment.rb#L20
    def apply
      each { |k, v| ENV[k] ||= v }
    end
```

That's why **Dotenv.with** works inspite of **merge!**
```ruby
  def with(*filenames, &block)
    filenames << ".env" if filenames.empty?

    filenames.reduce({}) do |hash, filename|
      hash.merge! block.call(File.expand_path(filename)) || {}
    end
  end
```
