### ISSUE TITLE
Dotenv.load/overload defaults to only .env

### ISSUE THREAD

**Issue by mpchlets** [bkeepers/dotenv#185]
It seems that Dotenv.load and Dotenv.overload defaults to using just .env - I would expect it to use the same: .env -> .env.#{Rails.env} -> .env.local defaults

[See these line](https://github.com/bkeepers/dotenv/blob/c11eb70646cd44a58b62fa15205a3ce2336f2331/lib/dotenv.rb#L20-L21)

     def self.with(*filenames, &block)
        filenames << '.env' if filenames.empty?

I would want this to include .env.local and .env.#{Rails.env} - I know I can pass it, but I assume that is the default anyhow. I don't mind making the Pull Request if that is the desired behavior for the gem

**Comment by bkeepers** [comment]
Both `.load` and `.overload` only ready from `.env` by default. Here is the Rails integration that loads multiple files. If you need anything more than that, I would just recommend using `dotenv` and not `dotenv-rails` and loading things manually.

**Comment by bkeepers** [comment]
Sorry, here' is the rails configuration: https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L27-L31

**Comment by mpchlets** [comment]
How about just a mention of this in the README, it is very confusing.
