### ISSUE TITLE
.env is overriding .env.test

### ISSUE THREAD

**Issue by nisevi** [bkeepers/dotenv#186]
Hello. I would like to share with you something that is happening to me when I try to set an environment variable through .env.test file for testing purpose.

I have a file ".env" with the following code:

    SOME_KEY_API="ENV_KEY"

and as I want to test some behavior I've created the file ".env.test" with the following code:

    SOME_KEY_API="TEST_KEY"

and as it says the README file: **"Variables defined in .env.<current environment> will override any values set in .env or already defined in the environment."**

so when check the environment while I'm testing, Rails.env is test, but when I check my ENV, SOME_KEY_API still is ENV_KEY. I was debugging the flow of the info through the gem and I was able to see that in the last iteration, in this part of the code:

**"dotenv-2.0.1/lib/dotenv.rb"**

    # Internal: Helper to expand list of filenames.
    #
    # Returns a hash of all the loaded environment variables.
    def with(*filenames, &block)
      filenames << ".env" if filenames.empty?

      filenames.reduce({}) do |hash, filename|
        hash.merge! block.call(File.expand_path(filename)) || {}
      end
    end

"hash" has my SOME_KEY_API="TEST_KEY" and when the "merge" is applied is replacing "TEST_KEY" with "ENV_KEY". So finally for testing environment I never get the "TEST_KEY".

Could you check this behavior? and please tell me if you need more info about it.

**Comment by bkeepers** [comment]
I'm not able to duplicate your issue. Can you give more information about how your app is configured and how you're seeing the behavior?

 Here's what I did:

```
$ rails new foobar
$ echo 'gem "dotenv-rails" >> Gemfile
$ bundle
$ echo "FOO=.env" > .env
$ echo "FOO=.env.test" > .env.test
$ RAILS_ENV=test rails runner "puts ENV['FOO']"

.env.test
```

Rails 4.2.0
dotenv 2.0.1

**Comment by bkeepers** [comment]
@nisevi let me know if you're still having problems.
