### ISSUE TITLE
Generate a dotenv file ?

### ISSUE THREAD

**Issue by grosser** [bkeepers/dotenv#187]
I might have a weird usecase where I generate a .env file from a hash for our deployment tool [samson](https://github.com/zendesk/samson/pull/397) would that be a feature you want to add / should I make a PR once I have the generator code written ?

@bkeepers

**Comment by bkeepers** [comment]
Hi @grosser, that's definitely interesting. Can you tell me a little more about what it and what it would look like to use it?

**Comment by grosser** [comment]
basically just escaping, but then I can also add nice tests to make sure parser and generator can talk to each other

```Ruby
Dotenv::Generator.call({"FOO" => "BA RRRR", "BAZ"=>"111"})
=> "FOO=BA\\ RRRR\nBAZ=111\n"
```

**Comment by grosser** [comment]
https://github.com/bkeepers/dotenv/pull/188
