### ISSUE TITLE
How to nest lines

### ISSUE THREAD

**Issue by turgs** [bkeepers/dotenv#197]
What syntax do I need to use to nest lines?  
For instance:

    AAA=heyhey
    BBB="#{AAA} boomstakalaka"

At the moment, line `BBB` literally outputs as `#{AAA} boomstakalaka` rather than `heyhey boomstakalaka` and I'm not sure what needs to change.

**Comment by bkeepers** [comment]
Hey @turgs. shell-style variable expansion is supported:

```
BBB="${AAA} boomstakalaka
```
