### ISSUE TITLE
Not respecting env variables set out of .env

### ISSUE THREAD

**Issue by zdennis** [bkeepers/dotenv#200]
I was trying to override a env variable set in my local .env when running a rake task from the command line, but it didn't appear to take.

```
rails --version   # => Rails 4.2.1

rails new wat && 
  cd wat && 
  echo "gem 'dotenv-rails'" >> Gemfile && 
  bundle && 
  echo 'FOO=bar' > .env

# This should print out bar
bundle exec rails runner "puts ENV['FOO']"

# I was expecting this to print out baz, but it printed out bar
FOO=baz bundle exec rails runner "puts ENV['FOO']"

# Also tried this but it too printed out bar
export FOO=baz && bundle exec rails runner "puts ENV['FOO']"
```

Am I expecting the right behavior?

**Comment by eugeneius** [comment]
I get the behaviour you expected - the env variable takes precedence over the `.env` entry:

```
$ bundle exec rails runner "puts ENV['FOO']"
bar
$ FOO=baz bundle exec rails runner "puts ENV['FOO']"
baz
```

dotenv provides a `.load` method which keeps any values that are already set in the environment, and an `.overload` method which overwrites them. The `dotenv-rails` gem calls `.load`: https://github.com/bkeepers/dotenv/blob/v2.0.2/lib/dotenv/rails.rb#L27

Did you try using a different variable, to make sure Rails is picking up your environment correctly?

```
BAR=baz bundle exec rails runner "puts ENV['BAR']"
```

**Comment by oboxodo** [comment]
I think I have the same (or similar) problem.

```bash
$ ./bin/rails --version
Rails 4.1.13
$ ./bin/spring --version
Spring version 1.3.6
$ grep dotenv Gemfile.lock
    dotenv (2.0.2)
    dotenv-rails (2.0.2)
      dotenv (= 2.0.2)
  dotenv-rails
$ ./bin/spring status
Spring is not running.
$ grep DEFAULT_NAV_VERSION .env*
DEFAULT_NAV_VERSION=1
$ ./bin/rails runner "puts ENV['DEFAULT_NAV_VERSION']"
1
$ ./bin/spring status
Spring is running:

25576 spring server | Quimbee | started 21 secs ago
25578 spring app    | Quimbee | started 21 secs ago | development mode
$ DEFAULT_NAV_VERSION=3 ./bin/rails runner "puts ENV['DEFAULT_NAV_VERSION']"
1
$ ./bin/spring stop
Spring stopped.
$ DEFAULT_NAV_VERSION=3 ./bin/rails runner "puts ENV['DEFAULT_NAV_VERSION']"
3
$ ./bin/rails runner "puts ENV['DEFAULT_NAV_VERSION']"

$ ./bin/spring status
Spring is running:

25671 spring server | Quimbee | started 33 secs ago
25672 spring app    | Quimbee | started 33 secs ago | development mode
```

Something is not right, and it seems to be related to spring...

**Comment by Papipo** [comment]
I am using `Dotenv.load` and I am having the same issue.

**Comment by siegy22** [comment]
This is expected behaviour.

If you'd like to overwrite existing ones use `Dotenv.overload`. See #278

**Comment by eugeneius** [comment]
I don't think this is expected behaviour.

Environment variables should override `.env` entries when calling `.load`, as mentioned in https://github.com/bkeepers/dotenv/issues/278.

This issue describes a problem where `.env` entries are not overridden, i.e. users are seeing the `.overload` behaviour when calling `.load`. Switching to `.overload` won't help.

As suggested by [this comment](https://github.com/bkeepers/dotenv/issues/200#issuecomment-136898095), I think the cause is actually Spring: https://github.com/rails/spring/issues/420
