### ISSUE TITLE
Some escaped '$' characters are not unescaped

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/dotenv#207]
Reported by @BeattieM in https://github.com/bkeepers/dotenv/pull/203, there are a few instances where escaped `$` doesn't get unescaped:

```
FOO="bar\$"
FOO="\$\$"
```

**Comment by dhunnapotha** [comment]
I hope this pull request  https://github.com/bkeepers/dotenv/pull/222 fixes the issue
