### ISSUE TITLE
How should I store values with dollar signs ($)...(escaped, quoted)?

### ISSUE THREAD

**Issue by timkelty** [bkeepers/dotenv#214]
I have a .env file that is being parsed by both [PHP](https://github.com/vlucas/phpdotenv) and node [Node](https://github.com/motdotla/dotenv) implementations.

I'm asking here in the canonical repo, as this is more of a best practice question.

I have values that have literal dollar signs in them:

```
DB_PASS=DgaH$a43
```

Should I be quoting that, or escaping the dollar?
If I escape the dollar in my .env file, will I need to _unescape_ it when i use it?

So I guess it boils down to - should I be escaping the dollar in my .env file, or when I get the value with PHP or Node or whatever?

**Comment by bkeepers** [comment]
The Ruby implementation of dotenv follows follows bash as closely as possible, which means $ needs to be escaped unless it is in single quotes. These are all valid:

```
DB_PASS=DgaH\$a43
DB_PASS="DgaH\$a43"
DB_PASS='DgaH$a43'
```

The value in ruby will be unescaped.

**Comment by timkelty** [comment]
> The value in ruby will be unescaped.

Thanks! That's what I was looking for.

**Comment by tasaif** [comment]
This isn't working for me. The name of the environment variable is picked up but its value is an empty string.

**Comment by tasaif** [comment]
nvm I was accidentally using dot_env? Why is this package allowed to exist?
