### ISSUE TITLE
Add .env.#{Rails.env}.local

### ISSUE THREAD

**Issue by rap1ds** [bkeepers/dotenv#220]
What I read from the [rails.rb](https://github.com/bkeepers/dotenv/blob/299e497ba41395fc80b8b82c4e0cf2f7a503214a/lib/dotenv/rails.rb#L27) file, it seems that the Dotenv Rails integration is reading the following configuration files (in the following order): `.env.local`, `.env.#{Rails.env}` and `.env`. The problem with this is that it doesn't provide any way to locally override environment specific configurations.

I guess a quite common pattern in Rails development is to have two local databases, one for feature development and one for testing (btw. I'm not using `database.yml`, instead I'm using `DATABASE_URL` environment variable for DB configuration). Thus, I have the default `DATABASE_URL` set in `.env` AND in `.env.test`. With `.env.local` I can override the `DATABASE_URL` to match my own database user/password, but now the problem is that the same database is used for both, testing and development.

I [forked the library](https://github.com/sharetribe/dotenv/commit/5115144de5536fecbda02d5c0846ee95718b5797) and added a new file to the `Dotenv.load` file list: `.env.#{Rails.env}.local`. I tried that locally and it seems to work well.

What do you think, would it make sense to add a possibility to have local environment specific configuration file?

Thanks for building and maintaining Dotenv!

**Comment by rap1ds** [comment]
What do you thing about this? Does it make any sense?

I'm happy to close the issue if this is not a good idea.

**Comment by mhenrixon** [comment]
:+1:

**Comment by ryanshow** [comment]
I vote +1 for this change. In fact, we've encountered scenarios where .env.local can be extremely dangerous, allowing a developer to accidentally run tests against a database which they were developing against.

**Comment by nickhammond** [comment]
I never use `.env.local` and instead just have a `.env` file for development and then `.env.test` to override any development settings for tests. I find this works really well and leads to the least amount of confusion. `.env.test` and `.env.example` are committed to the repository while `.env` is created upon bootstrapping the project by copying `.env.example` to `.env` and gitignored. `.env.example` contains sane defaults to get the project up and running without any additional configuration.

**Comment by dmitryzuev** [comment]
And if you use `env.development`, will it work for you?

**Comment by nickhammond** [comment]
`.env` is my `.env.development`. `.env` should be whatever your primary environment is for that machine.

**Comment by bkeepers** [comment]
Since signing my name to EFNPA14 (Environment File Non-Proliferation Agreement of 2014), I am no longer allowed to advocate for more env files. :trollface: 

Seriously though,  `.env`, `.env.local`, `.env.test`, `.env.development` are all already loaded. If you need any more than that, I recommend just loading it manually in `application.rb`:

```ruby
require "dotenv"
Dotenv.overload(".env.#{Rails.env}.local")
```
