### ISSUE TITLE
"\xEF\xBB\xBF" error (on Windows)

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [bkeepers/dotenv#224]
@bkeepers @phlipper @shingara @metavida @Floppy:

Hi guys, :smile:

I got an ***"\xEF\xBB\xBF"* error for dotenv** while using the [*basics-of-authentication project*](https://github.com/github/platform-samples/tree/master/api/ruby/basics-of-authentication) from GitHub:

```bash
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/parser.rb:61:in `parse_line':
Line "\xEF\xBB\xBFGH_BASIC_CLIENT_ID=1234567890" doesn't match format (Dotenv::FormatError)

from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/parser.rb:45:in `block in call'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/parser.rb:44:in `each'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/parser.rb:44:in `call'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/parser.rb:34:in `call'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/environment.rb:13:in `load'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv/environment.rb:9:in `initialize'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:15:in `new'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:15:in `block (2 levels) in load'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:59:in `ignoring_nonexistent_files'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:14:in `block in load'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:46:in `call'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:46:in `block in with'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:45:in `each'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:45:in `reduce'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:45:in `with'
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/dotenv-2.0.2/lib/dotenv.rb:13:in `load'
from advanced_server.rb:6:in `<main>'
```

This error is occurring at **`dotenv-2.0.2/lib/dotenv/parser.rb`** on my Windows 10.

What's the problem?

> Read also the important issue on https://github.com/github/platform-samples/issues/78!

*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by SuriyaaKudoIsc** [comment]
I found out that the ***`\xef\xbb\xbf` error*** contains probably **invisible junk characters** *(at least from dotenv's perspective)* called the **Unicode BOM** (short name for: *byte order mark*).

This project thinks that those characters are part of the command that follows right after.

This is what I can see this message in the log, though the characters are escaped so they're visible to the naked eye: `Line "\xEF\xBB\xBFGH_BASIC_CLIENT_ID=1234567890" doesn't match format (Dotenv::FormatError)`!

(adapted from http://stackoverflow.com/a/5373369/5157221)

> How can I repair the *rest of the error warning*?

**Comment by metavida** [comment]
Agreed with your research. The solutions I've see involve either telling your text editor to not add the BOM character (either via a preference or by saving the file as ASCII instead of UTF-8) or by using an editor that doesn't insert the BOM character (I saw [one post recommend Notepad++](http://stackoverflow.com/questions/14464819/xef-xbb-xbf-comes-in-utf8-files-java))

**Comment by SuriyaaKudoIsc** [comment]
I use the **Windows Editor** but it also *doesn't work* with **Notepad++**. :anguished:
