### ISSUE TITLE
Default support for `.ruby-env`? (via rvm)

### ISSUE THREAD

**Issue by bf4** [bkeepers/dotenv#227]
ref: https://rvm.io/workflow/projects#project-file-ruby-version

> Some projects require extra configuration in environment; this is supported by using the .ruby-env file:

> echo "JRUBY_OPTS=--1.9" >> .ruby-env
This variable will be set when entering the project directory and reverted to its previous value when exiting the project directory.

**Comment by bkeepers** [comment]
It looks like it uses bash syntax, so you should be able to call:

```ruby
Dotenv.load(".ruby-env")
```

Let me know if that doesn't work for you.

**Comment by bf4** [comment]
yeah, that would work, of course.  Just though you might like the idea
