### ISSUE TITLE
API for reading without side effects?

### ISSUE THREAD

**Issue by vemv** [bkeepers/dotenv#231]
Hi!

I'd need dotenv functionality equivalent to `Dotenv.load`, but without resulting in having the ENV modified.

In other words, I just want the resulting hash (just like the one `Dotenv.load` returns).

`Dotenv.read` and `Dotenv::Railtie.read` sound like reasonable methods.

Do you think this is a feasible thing? One might think reading a `.env` file is super-easy, but if one takes into account features such as `export` and `$` substitutions, is looks more complex.

**Comment by bkeepers** [comment]
Hi @vemv, you can accomplish what you want by using the `Dotenv::Environment` class directly:

```ruby
env = Dotenv::Environment.new("path/to/file")
puts env["FOO"]
```

The result acts like a hash.  Let me know if you have any troubles with that.

**Comment by vemv** [comment]
Works perfectly, thanks so much!

You might want to add that to the readme.
