### ISSUE TITLE
Loading environment variables from env files in custom location

### ISSUE THREAD

**Issue by gocoolkris** [bkeepers/dotenv#235]
I would like to group the .env.<env> files in a custom location as opposed to the root. I understand that we need to modify https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb. This can be easily achieved by passing optional args to 'Dotenv::Railtie.load' method.

**Comment by gocoolkris** [comment]
The changes that can be applied with breaking existing code wouldbe 'dotenv/lib/dotenv/rails.rb' file

 def load(dir=Rails.root)
      Dotenv.load(
        dir.join(".env.local"),
        dir.join(".env.#{Rails.env}"),
        dir.join(".env")
      )
    end

Please let me know what needs to be done. Can i clone it and make changes and give a pull request?

**Comment by bkeepers** [comment]
Hi @gocoolkris! You just want to load files from a different location in your application? I think the easiest thing will be to just call `Dotenv.load` manually in your `config/applciation.rb`.

```ruby
root = "/etc/myapp"
Dotenv.load(
  File.join(root, ".env.local"),
  File.join(root, ".env.#{Rails.env}"),
  File.join(root, ".env")
)
```

Let me know if that doesn't work for your needs.

**Comment by gocoolkris** [comment]
Hi **@bkeepers** Yeah. i actually kinda figured and used that and it does work. But kinda would be handy to have this feature, as this would be also be backwards compatible. anyways thanks for response.
