### ISSUE TITLE
multiline doesn't work with double-quotes

### ISSUE THREAD

**Issue by gpolyn** [bkeepers/dotenv#243]
Hi,

With dotenv 2.1, Rails 4.2.5.1 and ruby 2.1.2 and a multiline key like the following in `.env.development`

``CERT_VALUE="-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQC...\n-----END RSA PRIVATE KEY-----"`

...I get the following

```
/Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 18 column 1 (Psych::SyntaxError)
	from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
	from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:318:in `parse'
	from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:245:in `load'
	from /Users/me/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5.1/lib/rails/application.rb:391:in `secrets'
```
This problem goes away under single quotes, but I think then `CERT_VALUE` is not in useable form.

Thanks,

G

**Comment by bkeepers** [comment]
@gpolyn it looks like the error is coming from the YAML parsing in `secrets.yml`. I'm assuming `CERT_VALUE` is used there? Can you paste how you're using it here?

**Comment by gpolyn** [comment]
@bkeepers thank you for that suggestion, which motivated me to re-formate my `CERT_VALUE`, which **solved the issue**. I suppose my initial attempt included some hidden characters that violated. (Related to my difficulty, this separate reference, [github.com/RailsApps/learn-rails/issues/34](url))
