### ISSUE TITLE
.env.local not loaded with foreman

### ISSUE THREAD

**Issue by poc7667** [bkeepers/dotenv#244]
When I inspect the generated file `/etc/init/sample_web.conf`

it only has the .env content by no .env.local .env.production content

How could I load  .env.production content with foreman

# Profile

    web: bundle exec puma -e production -C config/puma.rb -e production

# Generate upstart script  with Foreman

      sudo foreman export upstart /etc/init -a sample_web -u app_user 

# /etc/init/sample_web.conf (generated by Foreman export command)

    start on starting sample_web
    stop on stopping sample_web
    respawn
    setuid sample_user
    chdir /home/sample_user/workspace/sample_web/releases/20160303143446
    exec bundle exec puma -e production -C config/puma.rb

**Comment by bkeepers** [comment]
Hi @poc7667, foreman doesn't use dotenv any more and only loads `.env`. But it [looks like](https://ddollar.github.io/foreman/) there is a `-e` argument that you can use for multiple environment files:

```
foreman export upstart /etc/init -e .env,.env.production -a sample_web -u app_user 
```
