### ISSUE TITLE
Unsage in production

### ISSUE THREAD

**Issue by kvokka** [bkeepers/dotenv#248]
Hello,
I have some miss understanding about usage this gem in production. As I can see in docs, propper way is to use dotenv gem only in development and text env, but how to propper export variables in production?

Now I made
`export FOO=bar`
but I understand, that is not good. Also, if I have 2 or more configs from 1 template I must rename ENV vars.

Unforchunatly, readme and stackoverflow did not helped.

**Comment by bkeepers** [comment]
> how to propper export variables in production?

It depends on your deployment environment. Cloud hosts like Heroku have settings for environment variables. You can also remove the `:groups => [:development, :test]` config in your `Gemfile`, and create a `.env.production` file. This is not recommended, but people do it anyway.
