### ISSUE TITLE
README: detail how to commit the .env but have a different one in local

### ISSUE THREAD

**Issue by tuxayo** [bkeepers/dotenv#250]
> Should I commit my .env file?
I prefer to commit the .env file with development-only settings

I couldn't find how to have a different .env in local without risking to commit it again (with Git for example)

**Comment by Startouf** [comment]
I commit a .env.example file

**Comment by tuxayo** [comment]
That what I ended up doing but I understood that one could have a `.env` commited and a different `.env` in local.

I realize that even if there is a way to do that, that would be confusing and risky to manage.
A `.env.example` file is more explicit and forcing the user to know about that file (because they would have to rename it) could be a good thing actually.

**Comment by Hates** [comment]
You can use `.env.local` for your own local overrides. That can be added to your `.gitignore` or similar file.

**Comment by Startouf** [comment]
@Hates Oh right, I suppose I completely missed that part of the documentation.

**Comment by tuxayo** [comment]
Me too, so it's in fact already documented in the [readme](https://github.com/bkeepers/dotenv/blob/17f16f2ac05edb605dba7739ca8d49ebcc467461/README.md#multiple-rails-environments)
