### ISSUE TITLE
Add section about using in production

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/dotenv#254]
I often get questions like…

> The README says use `gem 'dotenv-rails', :groups => [:development, :test]`, but how does dotenv work in production when it's only in dev and test groups?

There should probably be a section in the README dedicated to advice on using dotenv in production. https://github.com/bkeepers/dotenv#multiple-rails-environments touches on this, so it might be worth just renaming that section and adding info on removing the `:groups => …` from the `Gemfile`.

**Comment by x-yuri** [comment]
I was about to ask this particular question. The page you mentioned says: "There are typically better ways to manage configuration in production environments." But it doesn't explain why. Because environment variables are usually set in shell startup files, not being loaded on the fly?

**Comment by bkeepers** [comment]
> Because environment variables are usually set in shell startup files, not being loaded on the fly?

Yep, or most cloud services like Heroku have APIs for managing configs.

**Comment by siegy22** [comment]
I always use this in production and I love it. All the environment variables are in the same place as the project itself. As I use git in my projects my project structure typically looks like this:

```
├── .env
├── .env.development
├── .env.production.sample
├── .env.test
└── .gitignore
```

In the .gitignore file I always add:

```
.env.local
.env.production
```

If I then deploy my app, I copy my `.env.production.sample` to `.env.production` and fill this with my production variables.

I could add something like this as a little inspiration into the README and remove the groups from `gem 'dotenv-rails', :groups => [:development, :test]`

**Comment by siegy22** [comment]
ping @bkeepers :smile:

**Comment by binhnguyen1512** [comment]
Please help me. Active my phone

**Comment by binhnguyen1512** [comment]
Binhnguyen1512@22fd2bef3eddb76b43a4e606a2ed0e071108bee242e768d9e315c0c7906929c

**Comment by binhnguyen1512** [comment]
[](url)

**Comment by siegy22** [comment]
@binhnguyen1512 What are all these comments?

**Comment by siegy22** [comment]
@bkeepers I like the bot. But could you just verify that you really want to close this issue? :grin: 
And you can have a look at my attempt (https://github.com/bkeepers/dotenv/issues/254#issuecomment-274742626)
