### ISSUE TITLE
Values don't work exactly as if given on command line

### ISSUE THREAD

**Issue by nathanl** [bkeepers/dotenv#256]
I just worked on a feature where JSON values could be given in an environment variable. For example:

```
 EMAILS=["one@example.com", "two@example.com"]
```

This would be parsed (`JSON.parse(ENV['EMAILS'])`) within the application.

Everything worked fine in local testing, but the tests failed on CI. In the CI configuration file, I had to wrap the value in single quotes:

```
 EMAILS='["one@example.com", "two@example.com"]'
```

This matches the way the command line works. With this script:

```
# example.rb
require 'json'
foo = ENV['FOO']
puts JSON.parse(foo).inspect
```

Running `FOO=["a","b"] ruby foo.rb` errors, but `FOO='["a","b"]' ruby foo.rb` outputs an array as expected.

Maybe I'm conflating several issues here, but I was surprised by the CI failure and I expect that Heroku would have behaved like the CI, not like my local tests.

**Comment by bkeepers** [comment]
Thanks for the report. Dotenv attempts to mimic bash in most cases, but it's incomplete. [lib/dotenv/parser.rb:24](https://github.com/bkeepers/dotenv/blob/e4cbe7e0cebc5c71412b3971677fa3d8091f4fd7/lib/dotenv/parser.rb#L24)  would need to be updated to exclude characters that have special meaning in bash.

This isn't a priority for me to fix, but I would welcome a pull request that makes the parser more strict.
