### ISSUE TITLE
LoadError: cannot load such file -- dotenv/rails-now

### ISSUE THREAD

**Issue by zakwanhaj** [bkeepers/dotenv#261]
Hi,

When I try to initialize Dotenv before anything else, I added the following line at the top of Gemfile based on your advice in the readme:

```
gem 'dotenv-rails', groups: [:development, :test], require: 'dotenv/rails-now'
```

It works properly on my machine. But when I tried to deploy it on production server, I am getting this error: 

```
SSHKit::Command::Failed: rake exit status: 1
rake stdout: rake aborted!
LoadError: cannot load such file -- dotenv/rails-now
```

Is there any way to not load the gem in production environment? or is this a bundler bug?

**Comment by bkeepers** [comment]
@zakwanhaj hmm, I've never seen this.

Anyone else experienced this?

**Comment by dinjas** [comment]
Not sure if it is related, but I was getting this error earlier today when I had inadvertently used: `gem 'dotenv', groups: [:development, :test], require: 'dotenv/rails-now'` instead of `gem 'dotenv-rails', ...` in my Gemfile.

**Comment by stergiom** [comment]
Seem to be having a similar issue with requiring `dotenv/tasks`, works fine on my local setup but results in a **LoadError** on CI, can you think of anything I might have missed?
> https://community.codeship.com/t/rake-loaderror-dotenv-tasks/5182

**Comment by gee-forr** [comment]
Sorry to bump an old issue, but I have this *exact* problem too. Happy to give you as much info as you need.

**Comment by mach-kernel** [comment]
I have the same issue as stated above. Added the declaration to the top of my Gemfile as stated in documentation.

**Comment by IevgenRagulin** [comment]
I also face the same issue

**Comment by paulodeon** [comment]
If you are seeing a similar issue in development you may have an old version of dotenv

**Comment by Ghost---Shadow** [comment]
Bump

**Comment by crilam** [comment]
same issue here.
.rvm/gems/ruby-2.4.2/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require': cannot load such file -- dotenv/rails-now (LoadError)

**Comment by analyticalCat** [comment]
Same issue during docker-compose up

**Comment by msampaio49** [comment]
similar issue: 
/home/vagrant/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- dotenv (LoadError)

**Comment by danbernier** [comment]
Same issue just now, deploying to heroku.
