### ISSUE TITLE
README.md - gem 'dotenv-rails', :groups => [:development, :test]

### ISSUE THREAD

**Issue by silverdr** [bkeepers/dotenv#263]
Unless I understand something wrong, the doc suggests installation, which enables the gem only for the environments, which aren't of real concern and the true reason for using it in the first place. Shouldn't it suggest something like:

    gem 'dotenv-rails', :groups => [:production]
    if you like to use dotenv also in development and testing environment then use simply
    gem 'dotenv-rails'
?

**Comment by bkeepers** [comment]
dotenv was originally created to load configuration variables into `ENV` in development. See https://github.com/bkeepers/dotenv#multiple-rails-environments for more background.

**Comment by silverdr** [comment]
I see and understand - but will the `.env.production` file actually work if I install the gem according to the installation section of the top`README.md`? I am only about the perceived contradiction between 

https://github.com/bkeepers/dotenv#installation

and

https://github.com/bkeepers/dotenv#multiple-rails-environments
