### ISSUE TITLE
project title update:  include ruby and gem?

### ISSUE THREAD

**Issue by keen99** [bkeepers/dotenv#265]
currently the project title is just:

```
   Loads environment variables from `.env`.
```

After hitting a few repos (and issuing the wrong one) with nearly identical titles - perhaps something like:

```
  Ruby gem to load environment variables from `.env`
```

might be nicer?

(I'd PR it, but you can't PR that part to my knowledge...)

**Comment by franklinyu** [comment]
If you are [searching in GitHub](https://github.com/search?utf8=%E2%9C%93&q=dotenv) then there is a "language" badge for most repositories.

**Comment by bkeepers** [comment]
Thanks for the suggestion. The description has been updated.
