### ISSUE TITLE
Special characters and quotation

### ISSUE THREAD

**Issue by ekampp** [bkeepers/dotenv#267]
HI there. 

I have the need to load this string into the env via Dotenv: `bm%IEG^lkq$D-$wOsDmu`

This failed and gave me only this result: `bm%IEG^lkq-` and no more.

I tried quoting the string; same problem. I then tried escaping the `$` signs; same problem.

So I ended up having to both quote the string and escape the string, like this: `bm%IEG^lkq\$D-\$wOsDmu`

This was very unexpected. 

I'm unsure is this is an issue with Dotenv parsing the .env file or with the ruby environment parsing the information when it's loaded into the environment.

**Comment by adammessinger** [comment]
You might try base64-encoding your variable values. I've seen that suggested as a way to get around certain special characters being handled oddly by various platforms.

**Comment by ekampp** [comment]
HI @adammessinger, thanks for suggesting that, that is a good idea. 

Do you know if that will automatically unencode them, when they're loaded into the env, or if I need to do that my self in the application?

**Comment by robkorv** [comment]
@ekampp, I just noticed that I you don't use spaces in my `.env` it doesn't need escaping.

```ini
# this should work
MYVAR=bm%IEG^lkq$D-$wOsDmu
```

**Comment by stevendaniels** [comment]
I encountered a similar issue and noticed the following code:
```
module Dotenv
  module Substitutions
    # Substitute variables in a value.
    #
    #   HOST=example.com
    #   URL="https://$HOST"
    #
    module Variable
      class << self
        VARIABLE = /
          (\\)?         # is it escaped with a backslash?
          (\$)          # literal $
          (?!\()        # shouldnt be followed by paranthesis
          \{?           # allow brace wrapping
          ([A-Z0-9_]+)? # optional alpha nums
          \}?           # closing brace
        /xi
      ...
  end 
end
```
This code is called in `Dotenv::Parser.parse_value`. This is what's causing your special characters to get cut off. @bkeepers: is that the expected behavior?

There are two ways to avoid this issue.
1. Use single quotes for strings like that, e.g. `KEY='special$value'`. This works, but will probably cause problems because it is difficult to know what characters will cause dotenv to split the value for. 

2. Avoid using substitutions. There might be a cleaner way, but if you do the following, `Dotenv::Parser.instance_variable_set("@substitutions".to_sym, [])`, then dotenv will properly handle strings like `KEY=special$value`. This will prevent also it from substituting variables and shell commands.

**Comment by ekampp** [comment]
Substitutions should probably be documented in the readme (I didn't find them), or be opt-in, so people don't get surprised.

**Comment by robkorv** [comment]
Substitutions is the standard in a bash shell. I think that's why it's in here.
But yeah I also didn't expect it. And it took some time to figure out what was causing it.

As I set 12 random characters passwords through with .env I always have to be sure it doesn't contain a `$` in it.

**Comment by bkeepers** [comment]
As @stevendaniels points out, this is definitely an issue with variable substitution.  You can avoid it by putting the value in single quotes:

```
FOO_BAR='bm%IEG^lkq$D-$wOsDmu'
```

I updated the docs in #275 - https://github.com/bkeepers/dotenv#variable-substitution

**Comment by kirill-konshin** [comment]
Base64 helped with this.

**Comment by KasperGreen** [comment]
if you using dotenv-expand, need escaping **$**

FOO_BAR=bm%IEG^lkq\$D-\$wOsDmu

**Comment by eujinn** [comment]
I tried with single quote for the variable with $ value but it is still being skipped.
Any idea on this?

I am running this in reactjs with "dotenv": "^10.0.0".

**Comment by bkeepers** [comment]
@eujinn soubds like you are using the [JavaScript implementation of dotenv](https://github.com/motdotla/dotenv)

**Comment by ibibhu** [comment]
In a scenario I have something like this with json in .env:

    #Parsed by skiping after #: '[{"name":"dummy1",password:"Pass'
    destinations=[{"name":"dummy1",password:"Pass#1234"];

    #parsed to correct string : '[{"name":"dummy1",password:"Pass#1234"]'
    destinations=`[{"name":"dummy1",password:"Pass#1234"]`;

Ref:
dotenv vesrion: 16.0.1
https://www.npmjs.com/package/dotenv

backticks are supported (BACKTICK_KEY=\`This has 'single' and "double" quotes inside of it.\`)
