### ISSUE TITLE
Evaluating command line output on application bootup

### ISSUE THREAD

**Issue by dbslone** [bkeepers/dotenv#270]
I am currently trying to store a command line output in a ENV variable using:
`LOCALHOST="$(ipconfig getifaddr en0):5000"`

If I load the Rails console and access ENV['LOCALHOST'] => "10.0.64.201:5000"
But during application bootup in application_controller.rb if I use binding.pry or just a Rails.logger.info to see the value it returns `"$(ipconfig getifaddr en0):5000"`

I have tried placing Dotenv.load and Dotenv::Railtie.load before the logic that accesses the ENV  the response object shows the correct value (evaluated string) but when I attempt to access the value from ENV it returns the unevaluated string.

**Comment by bkeepers** [comment]
Hi @dbslone, that is strange. Are you using `foreman` to start your app? It has its own implementation of `.env` loading, which I don't believe supports command substitution.

**Comment by bkeepers** [comment]
@dbslone closing this, but let me know what you figured out.
