### ISSUE TITLE
`dotenv/rails-now` generic alternative

### ISSUE THREAD

**Issue by rgtk** [bkeepers/dotenv#271]
dotenv provides `dotenv/rails-now` which allows to use this gem by only adding single line of code for Rails app. It would be great to have something similar for [Sinatra or Plain ol' Ruby](https://github.com/bkeepers/dotenv/tree/e4cbe7e0cebc5c71412b3971677fa3d8091f4fd7#sinatra-or-plain-ol-ruby) apps especially when dotenv is used only within some Bundler groups. That could potentialy avoid writing code in application logic to handle different enviroments.

**Comment by bkeepers** [comment]
This was just added in https://github.com/bkeepers/dotenv/pull/252

```ruby
require "dotenv/load"
```

or in a Gemfile:

```
gem "dotenv", require: "dotenv/load"
```
