### ISSUE TITLE
environment-specific env configuration files

### ISSUE THREAD

**Issue by knzudgt** [bkeepers/dotenv#286]
I would like to use dotenv for setting in development Sentry's SENTRY_DSN variable, and checking out from version control the env file. So my main concern is to set this variable only for development.
Given for granted that I inserted the gem in both the development and test sections of the Gemfile, how can I tell dotenv to use this variable only in development?

As far as I have understood reading the documentation, I could create a specific .env.development file in the root of my application and define there my environment-specific variable(s). Is that enough and the only way to do it?

I came here after reading [an article](https://launchschool.com/blog/managing-environment-configuration-variables-in-rails) at launchschool.com where it is written that "yaml-like configs come baked in", which gave me the (probably wrong) idea that I could create a unique .env file and write specific sections for each environment using yaml notation. Is that possible?

That also might be interesting, but I could not find documentation in here.

**Comment by siegy22** [comment]
So you're using rails?

And mabye this section will help: https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use

**Comment by siegy22** [comment]
@knzudgt I updated the comment a bit :grin:

**Comment by knzudgt** [comment]
Thanks for the exaustive explanation :)
To tell the truth, I would rather follow the recommendation I found in the [Raven-Ruby GitHub page](https://github.com/getsentry/raven-ruby#raven-only-runs-when-sentry_dsn-is-set) than configuring Raven directly in config/application.rb, just because I do not want to check in my Sentry key to Git. The Raven-Ruby GitHub page advises against this, and recommends instead to set this variable in the desired environment.

Doing this in production is quite straightforward.
In development I chose to avoid to set variables in the Linux environment, because I might need different values for different applications.

That's why I decided to install dotenv.

**Comment by siegy22** [comment]
Yeah sure, if your repository is public, it's obvious that you need to hide it from public access..
At our company every time we have private repositories we just check it in.

And FYI I don't have this code block inside my `config/application.rb` I always write an initializer in `config/initializers/sentry.rb`.

dotenv is really good to store env variables, it keeps everything in place and if you have sensitive information like tokens/passwords I always prefer to use dotenv (to keep them secure, creating a sample) than configuring the environment variables on the according system :grin:

**Comment by siegy22** [comment]
You can also see my comment on #254 (https://github.com/bkeepers/dotenv/issues/254#issuecomment-274742626) to get a little inspiration.

If there are no more questions open, you can close this issue 😁

**Comment by knzudgt** [comment]
@siegy22 Last question, if you do not mind.
My repository is a private repository at BitBucket. 
In your opinion, would you say it is safe to check my Sentry key into Git or it is still advisable to avoid it?

**Comment by siegy22** [comment]
It's honestly opinion based.

In my opinion, you could check it in because only people have access who are also allowed.
And if it somehow gets leaked, it's not that critical, because the only thing you can do is report errors and infos with those credentials..
Anyway when you see some awkward things going on, you can revoke the sentry key: https://<my-sentry>/sentry/<project>/settings/keys/
