### ISSUE TITLE
Only .env file is loaded in non-Rails environments

### ISSUE THREAD

**Issue by arlandism** [bkeepers/dotenv#290]
There's a section in the [documentation](https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use) highlighting the different kinds of files loaded by dotenv (e.g. .env.development, .env.production, etc). After some trial, error, and investigation it looks like this is only true if you're using Rails:
- [Rails load](https://github.com/bkeepers/dotenv/blob/94eaa61494e44abc3af96d8f5717d911877b4903/lib/dotenv/rails.rb#L38)
- [Non Rails load](https://github.com/bkeepers/dotenv/blob/94eaa61494e44abc3af96d8f5717d911877b4903/lib/dotenv.rb#L43)

I think it'd be cool if that behavior worked on non Rails envs and I'd be happy to take a stab at adding it. Alternatively, I'd also be happy to add a note in the README mentioning the Rails env caveat.

**Comment by siegy22** [comment]
The problem is, that in rails we can easily find out on which environment we are. 
If we would do this for any other projects/frameworks, this project would be massive. Plus we don't know in what environment we are if it's not clear. I think you'll have to do that on your own in your project.

**Comment by arlandism** [comment]
Makes sense, thanks.
