### ISSUE TITLE
Loading ENV variables in db:seed and db:migrate

### ISSUE THREAD

**Issue by karlclement** [bkeepers/dotenv#294]
How would one load in variables from .env file into tasks such as `rails db:migrate` and `rails db:seed`

Thank you,

**Comment by siegy22** [comment]
What do you mean by `load in variables from .env file into tasks such as`?

I just tried it:

```ruby
# db/seeds.rb

puts ENV["FOO"]
```

```dotenv
FOO=bar
```

```bash
bin/rake db:seed
# => printing "bar"
```

**Comment by karlclement** [comment]
My `db:` commands must be ignoring the `.env.local` file ENV variables. Because when I run `rails db:seed`, this is the output:

![screen shot 2017-03-31 at 9 44 51 am](https://cloud.githubusercontent.com/assets/539188/24553068/e9d983be-15f6-11e7-9b45-5ec99ed306c7.png)

How do you initialize/include dotenv in your application? Thank you for your help

**Comment by siegy22** [comment]
I just require it in my Gemfile:

```ruby
gem 'dotenv-rails'
```

**Comment by karlclement** [comment]
@siegy22 doesn't load the `.env` file in my `db:` tasks.

**Comment by siegy22** [comment]
So in what environment are you?
Maybe you're looking for some values that are declared in `.env.production` while you're still in development environment?

**Comment by bkeepers** [comment]
@karlclement it should just work. 

What version of rails and dotenv are you using?

**Comment by karlclement** [comment]
@bkeepers @siegy22 I'm running Rails 5.0.2 and dotenv 2.2.0. It should be in development since I'm running a local Docker container

**Comment by siegy22** [comment]
I just had an issue loading my variables, I created a new rails 5.0.2 project.
And spring was auto inserted... And it was broken, because Spring doesn't reload the whole rails stack again. So the variables aren't loaded on startup everytime. I ended up restarting spring, it worked again.

**Comment by karlclement** [comment]
@siegy22 I tried that as well but it never loads ENV variables before doing a db:seed

**Comment by marckohlbrugge** [comment]
For what it's worth I was running into the same issue with my Rails app. Using the `dotenv-rails` gem instead of `dotenv` solved it for me.

**Comment by skplunkerin** [comment]
**Dotenv-rails** ended up not being the problem for me, I found that my issue was having a `$` in my variable value, I needed to wrap the value like `'[value]'`. Changing

```
DB_PASSWORD=$securepassword$
```

to:

```
DB_PASSWORD='$securepassword$'
```

>**NOTE:** `DB_PASSWORD="$securepassword$"` didn't work, use `'` instead of `"`
