### ISSUE TITLE
Data type mismatch

### ISSUE THREAD

**Issue by asnad** [bkeepers/dotenv#305]
I added export AUCTION_BID_INCREAMENT = 1000 in my .env file but why I'm getting "1000" (string) when I use it with ENV['AUCTION_BID_INCREAMENT']

**Comment by siegy22** [comment]
This is because the [ENV class](https://ruby-doc.org/core-2.2.0/ENV.html) only allows you to store strings as values. If you want to get the value as an Integer you should use `.to_i`:

```ruby
ENV["AUCTION_BID_INCREAMENT"].to_i # => 1000 (Numeric)
```
