### ISSUE TITLE
gem 'dotenv-rails', groups: [:development, :test]

### ISSUE THREAD

**Issue by atstockland** [bkeepers/dotenv#316]
Grouping the gem causes it to not load in development env.  This seems like a bundler issue, but I have not experienced this until attempting to use the dotenv gem...so, I'm starting here.

      group :test, :development do
          gem 'dotenv-rails'
      end

resulting in the following error when attempting to start the server or console 

      application.rb:11:in `<top (required)>': uninitialized constant Dotenv (NameError)

if I bundle the gem without grouping it...the server and console start as expected.  

I am not requiring or loading dotenv anywhere in my app.

### System configuration
    dotenv (2.2.1)
    dotenv-rails (2.2.1)

**Rails version**:
  'rails', '5.0.6'

**Ruby version**:
  ruby '2.3.3'

**Comment by atstockland** [comment]
One possible way to live with this might be to rename my .env file to .env.development.  My .env file is ignored...so, even in production dotenv won't find it and I am assuming won't affect heroku from loading vars from configs.

**Comment by siegy22** [comment]
Can you try `RAILS_ENV=development bin/rails c`?
Maybe there's a RAILS_ENV variable in your env saying that you want to start rails in production mode. You can check with the `env` command.

**Comment by thibaut-poullain** [comment]
I've got the same issue. My .env file is not loaded, or an old one is in cache or something...

I tried `Dotenv.load` in the rails console. It returns an hash with my correct .env. But when I test a env variable, It shows me an other value... 

I'm on Rails 5.1.4 and ruby 2.4.1

I'm using dotenv to load database and api credential. So I need to load my .env early.

This is my conf :

**gemfile** (I've got this in my gem file in **dev** and **test** env in a group)

`gem 'dotenv-rails', require: 'dotenv/rails-now'`

**application.rb** (before the class definition)
```
Bundler.require(*Rails.groups)
Dotenv::Railtie.load if Rails.env.development? || Rails.env.test?
```

I tried to write `gem 'dotenv-rails', require: 'dotenv/rails-now'` separatly in test and dev. Doesn't change anything, an old value is used...

I don't have anything in my initializer ;)
thx !

**Comment by thibaut-poullain** [comment]
After 4 hours to deal with the same issue, I figured it out.

It should be added to the documentation ;)

Spring doesn’t reload env variable. Use `spring stop` then `rails console` or `rails server` to reload the env vars.
If you want to do it automaticly : monitor the .env file :

#config/spring.rb
```
%w[
  .env
  .ruby-version
  .rbenv-vars
  tmp/restart.txt
  tmp/caching-dev.txt
].each { |path| Spring.watch(path) }
```

**Comment by micahlisonbee** [comment]
`spring stop` worked for me when the `.env.` file would not load into the Rails Console or `rails s` for the first time.
