### ISSUE TITLE
Feature Request: minimal source-able shell output

### ISSUE THREAD

**Issue by jasonkarns** [bkeepers/dotenv#322]
This is probably a strange request but here's the scenario:

Our projects are using the scripts to rule them all pattern. Many of these scripts rely on env vars that are set in .env, which we'd like to source.

We _could_ simply source them. But then we have to ensure the .env file exists... and add a linter comment b/c shellcheck complains about the sourced file not existing...

We _could_ do `. <(dotenv export)` but that dumps the _entire_ env. Which shouldn't hurt anything but just feels... blech. And that also prepends export to everything, which we don't really want. (We'd love to just have the env vars set for just the shell that does the sourcing.)

So short story: I'd love a flag that would behave the same as `dotenv export`, but doesn't prepend `export` and only dumps the variables that are actually defined in `.env`.

Thoughts?

**Comment by bkeepers** [comment]
👍 I've wanted the same thing in the past.

**Comment by jonmagic** [comment]
@jasonkarns any interest in implementing that feature? (New maintainer here so sorry if I missed other conversations or PRs about this)

**Comment by jasonkarns** [comment]
@jonmagic Ideally or practically? ;) yes, interest. but realistically speaking pretty low on my priority last at present.

**Comment by jonmagic** [comment]
> @jonmagic Ideally or practically? ;) yes, interest. but realistically speaking pretty low on my priority last at present.

Right on, I'm in the same ⛵️ right now. I'm going to close this as stale and maybe one of us will have time to revisit in the future!
