### ISSUE TITLE
Introducing new maintainers for dotenv

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/dotenv#326]
I have not been writing much Ruby lately, and as a result, have not been doing a very good job of maintaining this project. It's time to hand it over to some people that will take better care of it.

Say hello to @jessrudder, @jonmagic, and @cadwallion, who have all graciously volunteered to help out with maintenance.

Here's a list of suggestions to start with, but feel free to update it.

- [ ] document release process (basically just `rake release`)
- [x] Review [recently closed PRs with the `wontfix` label](https://github.com/bkeepers/dotenv/pulls?q=is%3Aclosed+is%3Apr+label%3Awontfix). These were closed by the stale app because I've not been paying attention to this repository
  - [x] https://github.com/bkeepers/dotenv/pull/291
  - [x] https://github.com/bkeepers/dotenv/pull/310
  - [x] https://github.com/bkeepers/dotenv/pull/313
  - [x] https://github.com/bkeepers/dotenv/pull/314
  - [x] https://github.com/bkeepers/dotenv/pull/315 (should be resolved by #325)
  - [x] https://github.com/bkeepers/dotenv/pull/320
- [x] Review [open PRs](https://github.com/bkeepers/dotenv/pulls?q=is%3Aopen+is%3Apr)

**Comment by jonmagic** [comment]
We haven't documented the release process yet but I'm going to note it here and close this issue as everything else is done.

```
rake dotenv:release
rake dotenv-rails:release
```

**Comment by bkeepers** [comment]
It's not documented in `rake -T`, but you can also just run `rake release`:

https://github.com/bkeepers/dotenv/blob/master/Rakefile#L19-L21
