### ISSUE TITLE
backward compatible to v2.2

### ISSUE THREAD

**Issue by spica831** [bkeepers/dotenv#337]
Version 2.3 is not backward compatible with features such as `parser`

Therefore, an error occurs in a framework other than Rails.

https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb#L33

Correction example
```
      def call(string, is_load = false)         # add default value
        new(string, is_load).call
      end
    end

    def initialize(string, is_load = false)     # add default value
      @string = string
      @hash = {}
      @is_load = is_load
    end
```

**dotenv version**:
2.3.0

**Ruby version**:
 2.4.2

**Comment by jonmagic** [comment]
Closed by https://github.com/bkeepers/dotenv/pull/338

Maintainers note: Looks like folks use the private API's so we'll have to think about if we want to remain backwards compatible for internal changes or just declare these API's as public?
