### ISSUE TITLE
Empty ENV is removed instead set as empty string in version 2.3

### ISSUE THREAD

**Issue by radeno** [bkeepers/dotenv#339]
### Steps to reproduce
In file `.env.development` i have these variables:
```
DATABASE_PASSWORD=
DATABASE_USERNAME=root
DATABASE_HOST=/tmp/mysql.sock
```

### Expected behavior
Variables should be parsed as:
```
 "DATABASE_PASSWORD"=>"",
 "DATABASE_USERNAME"=>"root"
 "DATABASE_HOST"="/tmp/mysql.sock"
```

### Actual behavior
In 2.3 missing whole keys `DATABASE_PASSWORD` and also `DATABASE_USERNAME ` because it is next after empty env variable.

Everything OK in 2.2

### System configuration
**dotenv version**: 2.3

**Rails version**: 5.2

**Ruby version**: 2.5

**Comment by radeno** [comment]
Problem is in multiline parser

When i define env vars with new line between them:
```
DATABASE_PASSWORD=

DATABASE_USERNAME=root

DATABASE_HOST=/tmp/mysql.sock
```

it is parsed as:

```
 "DATABASE_HOST"=>"/tmp/mysql.sock",
 "DATABASE_PASSWORD"=>"DATABASE_USERNAME=root"
```

**Comment by jonmagic** [comment]
Thank you for the bug report. Looking into potential solutions now.

**Comment by jonmagic** [comment]
We just shipped version 2.4.0 which removes the `Parse multiline values` support added in 2.3.0 and fixes the parsing regressions.

**Comment by wbotelhos** [comment]
@radeno @jonmagic To fix that, I just set an empty value, but it should represent a major release:

```
DATABASE_PASSWORD=''
```

**Comment by radeno** [comment]
@wbotelhos Yes we can pass empy string. But define variable without value is valid. No value as just empty string quotes is very rare.
