### ISSUE TITLE
ENV variable suitable for development, but not for production

### ISSUE THREAD

**Issue by kirylpl** [bkeepers/dotenv#349]
### Steps to reproduce
Put you ENV apikey in quotes like:
APIKEY='11111222224444'

### Expected behavior
Expected behavior that ENV variables will work BOTH on development and production environment without any difference.

### Actual behavior
APIKEY='11111222224444' is suitable by development environment but not for production.
Prod only read variable when I deleted quotes like:
APIKEY=11111222224444
You know, until I did this change it was a bit confusing.

### System configuration
**dotenv version**: 2.4.0

**Rails version**: 5.1.6

**Ruby version**: 2.5.1

**Comment by cadwallion** [comment]
Apologies, I am having a bear of a time getting this reproduced locally:

dotenv 2.5.0, rails 5.2.1, ruby 2.5.1 - single-quotes, double-quotes, or no-quotes work.
dotenv 2.4.0, rails 5.1.6, ruby 2.5.1 - single-quotes, double-quotes, or no-quotes work.

My setup is setting up a blank new rails app, adding a 'ping' controller that renders plain the time and 3 env vars defined in the .env.  `RAILS_ENV=production rails/server` to spin up production-mode server, and all 3 values are being displayed.

Is there any more information that can be provided to me about the structure of your .env files, without compromising security?  I'm struggling to reproduce to be able to fix.
