### ISSUE TITLE
The `overload` method is not available on dotenv-rails

### ISSUE THREAD

**Issue by dkarter** [bkeepers/dotenv#352]
I was wondering if there is a specific reason why the `overload` does not exist on the Rails version, is this an intentional or unintentional omission? I don't mind opening a PR if there's no objection to adding it. Seems like a pretty simple addition.

### Steps to reproduce
Try calling `Dotenv::Railtie.overload`

### Expected behavior
Method should exist and act similarly to how Dotenv.overload does.

### Actual behavior

```
NoMethodError:
  undefined method `overload' for Dotenv::Railtie:Class
```

### System configuration
**dotenv version**: 2.2.1

**Rails version**: 5.1

**Ruby version**: 2.4.1

**Comment by dkarter** [comment]
@bkeepers shall I open a PR for this? Thanks

**Comment by jonmagic** [comment]
> @bkeepers shall I open a PR for this? Thanks

@dkarter I'm wondering if you could overload using `Dotenv` instead [since the railtie just used that under the hood](https://github.com/bkeepers/dotenv/blob/d749366b6009126b115fb7b63e0509566365859a/lib/dotenv/rails.rb#L38)?

```ruby
require 'dotenv'
Dotenv.overload
```

**Comment by dkarter** [comment]
@jonmagic I'm not sure how that would work given that `dotenv_files`, which `Dotenv.load/overload` are taking as an argument, is a privately defined method inside of `Dotenv::Railtie`.

![image](https://user-images.githubusercontent.com/551858/47250725-5d8c0480-d3ec-11e8-8d0b-433b9d6cc375.png)
