### ISSUE TITLE
Gemfile Dependencies

### ISSUE THREAD

**Issue by bnd5k** [bkeepers/dotenv#364]
First, thanks for your work on this library.  I use it often and love it.

This is more of a question than an issue. 

Why are Nokogirl and Rack dependencies of this project?  

https://github.com/bkeepers/dotenv/blob/master/Gemfile#L15-L23

I don't see them being used anywhere in the production code or the tests.

Thanks.

**Comment by jonmagic** [comment]
Great question, I'm not actually sure except that it looks like they were added to fix failing CI? https://github.com/bkeepers/dotenv/pull/274
