### ISSUE TITLE
dotenv-rails 2.6.0

### ISSUE THREAD

**Issue by aried3r** [bkeepers/dotenv#366]
Hey! This is pretty much a duplicate of https://github.com/bkeepers/dotenv/issues/335 except for version 2.6.0. I guess there was another hiccup in the release process?

Is this automated somewhere? :)

**Comment by jonmagic** [comment]
Gah, that’s my bad. It’s not automated but we do have a release task list I was supposed to follow. Will get it fixed up in a bit and look into automation. Thanks!

**Comment by jonmagic** [comment]
https://rubygems.org/gems/dotenv-rails/versions/2.6.0
