### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by jonmagic** [bkeepers/dotenv#367]
I keep forgetting to publish the dotenv-rails gem in addition to the dotenv gem when we do a new release. Need to automate the whole process. Good candidate for GitHub Actions?

**Comment by cadwallion** [comment]
Happy to take this on this morning via Actions, was looking at something similar for another project anyway. :D

**Comment by jonmagic** [comment]
> Happy to take this on this morning via Actions, was looking at something similar for another project anyway. :D

Awesome!

**Comment by joelvh** [comment]
@cadwallion would love to see how this is achieved with Actions! Any way to share your implementation? Thanks!

**Comment by cadwallion** [comment]
Absolutely!

**Comment by cadwallion** [comment]
Completed by #369
