### ISSUE TITLE
Feature Request for CLI: Print usage on -h or --help

### ISSUE THREAD

**Issue by olleolleolle** [bkeepers/dotenv#371]
### Steps to reproduce

It would be cool if:

```bash
$ dotenv --help
```

presented usage.

### Expected behavior

Print usage.

### Actual behavior

It tries to read the .env file `-h`.

### System configuration

**dotenv version**: latest release.

**Ruby version**: 2.5.3

**Comment by cadwallion** [comment]
Thank you for reporting, this has been added via #374 and released as of 2.7.0!
