### ISSUE TITLE
Test environment stomping over development environment

### ISSUE THREAD

**Issue by rlugge** [bkeepers/dotenv#373]
### Steps to reproduce

This may be me not understanding some aspect of the documentation on how various `.env` files work.  There's a pretty big chart showing the different files, but it's a little lean on details on how to interpret it.

Create `.env`, `.env.development`, and `.env.test` files.  Load .env up with shared material, and the .development and .test with distinct material (live vs test credentials for Twillio in my case).

I'm including dotenv into my project via my gemfile:

    group :development, :test do
      # Environment Variables
      gem 'dotenv'

      # ...many more dev / testing gems
    end

### Expected behavior

I'd expect the contents of `.env.development` to be used exclusively in the development environment, and `.env.test` to be used exclusively when loading up the test environment.  The test environment is activated via rspec, or `rails c RAILS_ENV=test`, or similar commands.

### Actual behavior
When I start up the console using rails c and examine my environment variables, my `.env.test` file is overriding my `.env.development` file's variables.  When I examine my twilio environment keys, I can see that I'm getting the test ones even when in development.

### System configuration
**dotenv version**: 2.6.0

**Rails version**: 5.1.3

**Ruby version**: 2.3.1

**Comment by cadwallion** [comment]
👋 Thank you for the report!  Can you provide the snippet where you activate Dotenv in your Rails application?  

My first thought is that (based on the snippet you have provided) that since you're using dotenv in a Rails app, that using `dotenv-rails` instead of `dotenv` will resolve the problem, as it integrates a Railtie that should trigger the appropriate environment.

**Comment by rlugge** [comment]
@cadwallion when I went to give you the relevant data, I found the problem.  My loading code was wrong front to back.  This was completely user-error on my part.  The perils of coming back to a project after not touching it significantly for two years, combined with trying to work through a nice head cold.

**Comment by cadwallion** [comment]
No worries, glad to hear things have been resolved!
