### ISSUE TITLE
Dotenv with Rails 4.2.11 Doesn't Work with RSpec

### ISSUE THREAD

**Issue by EvetteM** [bkeepers/dotenv#378]
### Steps to reproduce
1. Gemfile contains:
...
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'mysql2', '0.4.10'
gem 'rails', '4.2.11'
....
Run: bundle update
- all installations work as expected
2. {root dir}/.env.test contains:
my_key='xxxxxxxx'

3. running an rspec test:
rspec spec/models/integration_mailchimp_spec.rb 

An error occurred while loading ./spec/models/integration_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

Bundler::GemRequireError:
  **There was an error while trying to load the gem 'dotenv/rails-now'.
  Gem Load Error is: undefined local variable or method `dotenv_files' for #<Dotenv::Railtie:0x007ff51b4eada0>**
  Backtrace for gem load error is:
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/dotenv-rails-2.7.1/lib/dotenv/rails.rb:38:in `load'
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/dotenv-rails-2.7.1/lib/dotenv/rails.rb:51:in `load'
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/dotenv-rails-2.7.1/lib/dotenv/rails.rb:55:in `block in <class:Railtie>'
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:27:in `each'
  /Users/phoenix/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:27:in `on_load'

==========
Issue is that the dotenv_files variable isn't being set.
If I edit this file: view ~/.rvm/gems/ruby-2.3.3/gems/dotenv-rails-2.7.1/lib/dotenv/rails.rb

Moving the lines 59-66 to before the config.before_configuration { load } it works.
The file now looks as below:
    def dotenv_files
      [
        root.join(".env.#{Rails.env}.local"),
        (root.join(".env.local") unless Rails.env.test?),
        root.join(".env.#{Rails.env}"),
        root.join(".env")
      ].compact
    end

    config.before_configuration { load }

### Expected behavior
All rspec tests should pass as the environment variables would be read.

### Actual behavior
Fails to run rspec as it requires an env variable to be loaded, which doesnt happen as dotenv-files doesnt get set.

### System configuration
dotenv (2.7.1)
dotenv-rails (2.7.1)
Rails 4.2.7
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin17]

**Comment by siegy22** [comment]
Would you mind renaming the issue to something that includes "rspec" as it works with rails 4.2.11.x (with minitest) 😄

**Comment by EvetteM** [comment]
Fair enough - done!

**Comment by cadwallion** [comment]
Thank you for reporting, and apologies for the regression!  I'll take a look at this issue today and report back as soon as I can.

**Comment by cadwallion** [comment]
👋 I am having trouble reproducing this.  I have setup an example Rails 4.2.11 app with rspec-rails and the latest dotenv in the same configuration you have specified with a .env file containing a DATABASE_URL that MySQL is connecting to, as well as a REQUIRED=foo var.

I was able to run DB tests, as well as `expect(ENV["REQUIRED"]).to eql("foo")`.  I'm not sure what next steps to try to reproduce what you're experiencing, unfortunately.
