### ISSUE TITLE
Regression in 2.7.1: Ignores quote in arguments

### ISSUE THREAD

**Issue by walro** [bkeepers/dotenv#381]
As the title of the issue, it seems like quotes are ignored. Looking at https://github.com/bkeepers/dotenv/compare/v2.7.0...v2.7.1 it would seem like this was an inadvertent effect of https://github.com/bkeepers/dotenv/pull/376

### Steps to reproduce
```bash
$ gem install dotenv
Fetching dotenv-2.7.1.gem
Successfully installed dotenv-2.7.1
Parsing documentation for dotenv-2.7.1
Installing ri documentation for dotenv-2.7.1
Done installing documentation for dotenv after 0 seconds
1 gem installed

$ cat dotenv.sh 
#!/bin/sh

echo $1

$ dotenv ./dotenv.sh "dotenv envdot"
dotenv

$ gem uninstall dotenv -v 2.7.1
Successfully uninstalled dotenv-2.7.1

$ gem install dotenv -v 2.7.0
Fetching dotenv-2.7.0.gem
Successfully installed dotenv-2.7.0
Parsing documentation for dotenv-2.7.0
Installing ri documentation for dotenv-2.7.0
Done installing documentation for dotenv after 0 seconds
1 gem installed

$ dotenv ./dotenv.sh "dotenv envdot"
dotenv envdot
```

### Expected behavior
It should keep quoted argument as a single argument, as in previous versions of dotenv.

### Actual behavior
It seems to split quoted arguments on space, ignoring the quotes.

### System configuration
**dotenv version**: 2.7.1

**Rails version**: n/a

**Ruby version**: 2.6.1

**Comment by cadwallion** [comment]
Thank you for reporting!  I'll investigate this issue today and get back to you as soon as I can.

**Comment by cadwallion** [comment]
@walro Could you please provide the dotenv.sh script you were using to test in the repro steps?  I'd like to be as consistent as possible.  Thanks!

**Comment by dentarg** [comment]
@cadwallion it is there, it is really short:

```sh
#!/bin/sh

echo $1
```

**Comment by cadwallion** [comment]
Oh, apologies.  Thanks!

**Comment by cadwallion** [comment]
Thank you so much for the clear and concise report!  #382 should resolve the issue (and also dramatically improved the maintainability of the CLI) for you.  I'll cut a 2.7.2 gem in the next 24 hours as well.
