### ISSUE TITLE
documentation fix, Dotenv::Railtie.load only if proper environment

### ISSUE THREAD

**Issue by estani** [bkeepers/dotenv#386]
The Documentation suggests adding the gem for only development and test:

    gem 'dotenv-rails', groups: [:development, :test]

But then suggest loading it for all environments:

    Dotenv::Railtie.load

This won't work in production. So I suggest extending the docs to this:

    if ['development', 'test'].include? Rails.env
      Dotenv::Railtie.load if defined? Dotenv
    end

The first fi is required to mimic the gem dependency. The second one, which seems not needed, is a special case for Heroku, which seems to compile without development but then starts rake in development. (makes no sense, but so it seems to be working)

**Comment by cadwallion** [comment]
Thank you @estani  for reporting this discrepancy!

Is the first `if` even needed, in this case?  If we're only loading dotenv in development and test, the only time `Dotenv` will be defined is in development and test.
