### ISSUE TITLE
Question about Dotenv.load

### ISSUE THREAD

**Issue by coding-bunny** [bkeepers/dotenv#388]
If I use Dotenv.load in a plain Ruby app, will it also load automatically other files if I have them defined and the RAILS_ENV variable set? Or do I need to manually load them?

**Comment by siegy22** [comment]
Short answer: you have to manually load them.

Long answer:
If you want the rails behaviour, you would have to do `require 'dotenv/rails'` which would fail unless you're using rails. The reason for this is that dotenv hooks [itself into the rails plugin pipeline](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L32).

**Comment by coding-bunny** [comment]
Okay, then I did it right!

We copied the logic of the rails loader and just load them ourselves in the correct order.
Thanks for the clarification.
