### ISSUE TITLE
Conflict with docker-compose 1.24.0

### ISSUE THREAD

**Issue by jonmchan** [bkeepers/dotenv#389]
The latest version of docker-compose (1.24.0) errors instead of silently fails when the `.env` file has whitespaces in it, such as with `export VAR=FOO`. As such, users using the latest version of docker-compose with the export syntax will not be able to run docker-compose. The prior behavior was that any lines with whitespaces was silently ignored, now it errors out and fails. 

Although I do not believe it should be dotenv responsibility to fix this issue, I wanted to bring it up here so that the dev team can be aware of it. If docker-compose won't change, you may have to at least add something into a FAQ or something.

Related issues:
https://github.com/docker/compose/issues/6511
https://github.com/docker/compose/issues/6741

**Comment by morganchristiansson** [comment]
ruby-dotenv per README works with and without export keyword. Using without export is compatible with docker-compose.

If using export keyword latest docker-compose falis with error whereas previously value was ignored.

**Comment by jonmchan** [comment]
export keyword is useful for being compatible with bash/sh `source .env`. Not sure if we're trying to juggle with too many areas of compatibility here.

**Comment by morganchristiansson** [comment]
I agree. However at least docker-compose will ignore lines starting with export.

**Comment by jonmchan** [comment]
that is why i'm reporting the issue - docker-compose 1.24.0 no longer ignores the lines starting with export - it is a hard fail in docker-compose at this point.
