### ISSUE TITLE
uninitialized constant Dotenv

### ISSUE THREAD

**Issue by JoseCed** [bkeepers/dotenv#390]
### System configuration
**dotenv version**:

**Rails version**:
2.5.1
**Ruby version**:
5.2.1

Caused by:
NameError: uninitialized constant Dotenv

https://gist.github.com/JoseCed

**Comment by cadwallion** [comment]
👋 Greetings!  I believe if you add a `require "dotenv/rails"` to your Capfile you should have your error remediated.
