### ISSUE TITLE
Web Console is activated in the test environment when running parallel:spec

### ISSUE THREAD

**Issue by klyonrad** [bkeepers/dotenv#395]
### Steps to reproduce

1. `bundle exec rake parallel:spec`

Show how you included dotenv (Gemfile).
```ruby
gem 'web-console', group: :development

group :development, :test do
  gem 'dotenv-rails'
end
```

### Expected behavior

Tests run in test environment.

### Actual behavior

Tests don't start running.

```
Web Console is activated in the test environment. This is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it in the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false
```

When I execute

```
RAILS_ENV=test bundle exec rake parallel:spec
```

The tests actually run fine

### System configuration
**dotenv version**:
2.7.4
**Rails version**:
5.2
**Ruby version**:
2.6.2

**Comment by klyonrad** [comment]
I suspect this comes from https://github.com/bkeepers/dotenv/pull/384

**Comment by klyonrad** [comment]
https://github.com/bkeepers/dotenv/issues/289 Looks very similar

**Comment by Dantemss** [comment]
I can confirm that dotenv-rails 2.7.3 and 2.7.4 break `rake parallel:spec` if `web-console` is also in the Gemfile (under the development group).

**Comment by florianroesler** [comment]
What is the state on this issue? I have just updated the gems in one of my project that is using parallel:spec and now I am seeing the mentioned error. 

`web-console` is in the development group and dotenv is at version 2.7.5.

**Comment by StanBoyet** [comment]
Hello,
If I may, the issue is not resolved and is still preventing us from running our test suite with `bundle exec rake parallel:spec` since we updated

**Comment by anicholson** [comment]
It's kludgy, but prepending `RAILS_ENV=test` to the rake command resolved this issue for me. Given #384, sounds like a race condition :grimacing:

**Comment by krtschmr** [comment]
still going string
