### ISSUE TITLE
Dotenv::Railtie.overload

### ISSUE THREAD

**Issue by dennisvandehoef** [bkeepers/dotenv#401]
Can you please add `Dotenv::Railtie.overload`

currently to combine overload in a Rails app, `Dotenv::Railtie` and `#overload` I came up with the following line `Dotenv.overload(*Dotenv::Railtie.send(:new).send(:dotenv_files))`, wich off course is a really ugly hack ;)

**Comment by dam13n** [comment]
Let's get this in. Damn stale bot pretty annoying -this issue isn't old at all.

**Comment by siegy22** [comment]
@cadwallion Would you mind taking a look at this?
