### ISSUE TITLE
New release of dotenv-rails?

### ISSUE THREAD

**Issue by connorshea** [bkeepers/dotenv#410]
The Rails 6.1 beta is supposed to be dropping sometime within the next few weeks, so I was wondering if we could get a new release of the gem to get the change from #404? :) Thanks!

**Comment by cadwallion** [comment]
Sorry for the delay on this, I was on paternity leave and just now catching up.  Here's a fresh [2.7.6](https://github.com/bkeepers/dotenv/releases/tag/v2.7.6) release!
