### ISSUE TITLE
Can't load variables in .env

### ISSUE THREAD

**Issue by longhoangwkm** [bkeepers/dotenv#411]
### Steps to reproduce
```
$ rails console
$ ENV['AMZ_URL']
```
Paste your env using:
```bash
AMZ_URL="https://www.amazon.com/"
```

### Expected behavior
=> "https://www.amazon.com/"

### Actual behavior
nil 

### System configuration
**dotenv version**: dotenv-rails (2.7.5)

**Rails version**: Rails 5.2.4.2

**Ruby version**: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]

I downgraded to dotenv-rails (2.7.2) and it works

**Comment by scottburton11** [comment]
Can confirm above ^ 
dotenv-rails 2.7.5 isn't loading in Rails 6.0.3. dotenv-rails 2.7.3 does.

**Comment by SFzxc** [comment]
Up!
