### ISSUE TITLE
Environment loading change in 2.7.6 is wrong

### ISSUE THREAD

**Issue by amilligan** [bkeepers/dotenv#415]
[This pull request](https://github.com/bkeepers/dotenv/pull/405) changed the default rake task to force load the Rails test environment.  

Setting aside any argument about how test vs. development environment in rake, installing a gem should not change the behavior of the default rake task.  Not every rake task is for running tests, and the default rake task very well may include tasks that are not test-specific.

To reproduce, simply create a default rake task with non-test tasks.  We use license_finder, brakeman, etc.  Given a non-test tasks dependent on running in the development environment the default task fails, fails to run, or gives incorrect results.

**Comment by cadwallion** [comment]
Apologies, I'll get this rectified today.

**Comment by amilligan** [comment]
Thanks, we appreciate it.

**Comment by amilligan** [comment]
@cadwallion Any chance of an update on this?  I'm happy to provide a pull request, but I suspect it would just be a revert of the commit that made the change.

**Comment by googya** [comment]
i met the problem too. In a plain ruby file,  can not read Dotenv variables .

**Comment by taylorthurlow** [comment]
!notstale

**Comment by bkeepers** [comment]
This is fixed by #468 and will be included in the 3.0 release soon.
