### ISSUE TITLE
Could not find dotenv-2.7.6 in any of the sources

### ISSUE THREAD

**Issue by ohthepain** [bkeepers/dotenv#435]
### Steps to reproduce

I am doing a fastlane build for iOS.
> bundle exec fastlane iOS deploy

My Gemfile:
```
source "https://rubygems.org"

gem "dotenv"
gem "fastlane"
gem "pry"

```

I can see when I run `bundle install` that the correct gem is installed

`Using dotenv 2.7.6
`

> Could not find dotenv-2.7.6 in any of the sources

Paste your env using:
```bash
$ env | grep MYVARIABLETOSHOW
```

I don't understand this step:
```
$ env | grep MYVARIABLETOSHOW
Hi from bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

```

### Actual behavior
Error `Could not find dotenv-2.7.6 in any of the sources`

### System configuration
dotenv-2.7.6
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**Comment by bkeepers** [comment]
Hi @ohthepain, it looks like you're running into a general issue with your system configuration that is not related to ruby. Did you follow the directions of the output from `env`?

Closing since this issue appears unrelated to dotenv.
