### ISSUE TITLE
`Dotenv.load` call causes Rails app to be loaded twice

### ISSUE THREAD

**Issue by thisismydesign** [bkeepers/dotenv#442]
### Steps to reproduce

We had the following historical setup.

`Gemfile`
```
group :development, :test do
  gem 'dotenv-rails'
end
```

`application.rb`
```
if File.exist?('.env')
  require 'dotenv'
  Dotenv.load
end
```

Even though the `application.rb` part is not needed when using with rails, I wouldn't expect this setup to reload the whole app.

### Expected behavior

`Dotenv.load` doesn't load the whole rails app.

### System configuration
**dotenv version**: 2.7.6

**Rails version**: 7.0.1

**Ruby version**: 3.0.3

**Comment by bkeepers** [comment]
@thisismydesign thanks for the issue. Are you sure it's dotenv causing the app to reload? There is nothing in `Doenv.load` that should be requiring any files, so I can't imagine how this would be the cause. Can you duplicate this in a new Rails app?

**Comment by thisismydesign** [comment]
Couldn't reproduce anymore
