### ISSUE TITLE
Rake tasks in Rails always initialized in "development"

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/dotenv#45]
The first line of `Rakefile` in any rails app is:

```ruby
require File.expand_path('../config/application', __FILE__)
```

This causes dotenv to always be initialized in "development" (loading `.env` and `.env.development`) unless `RAILS_ENV` is explicitly set in the environment before running `rake`, which leads to unexpected results when running rake tasks that affect other environments. For example, put a variable in `.env.test` and run `rake test` to see that the variable is not properly loaded.

Dotenv currently [initializes as soon as the Railtie is loaded](https://github.com/bkeepers/dotenv/blob/ac382273b8421a8c302fd387e8e1240a8e20af5b/lib/dotenv/railtie.rb#L14) so `ENV` variables can be used in `config/application.rb` (see #10). Dotenv also [avoids overriding existing variables](https://github.com/bkeepers/dotenv/blob/ac382273b8421a8c302fd387e8e1240a8e20af5b/lib/dotenv/environment.rb#L44) so it doesn't clobber values set in the shell environment. So once dotenv has been initialized, changing the `RAILS_ENV` and re-initializing doesn't change anything.

If the [Rails boot process](http://api.rubyonrails.org/classes/Rails/Application.html#label-Booting+process) created a clear distinction between bootstrap, configuration, and initialization in the startup process, then dotenv could hook in before the configuration step. But unfortunately `config/application.rb` requires code and provides application configuration.

Here are a few options to fix this issue. I would love other suggestions.

1. Remove implicit environment support. Instead of automatically loading `.env.test`, we could add a `:force` option and the README could encourage users to add `Dotenv.load '.env.test', :force => true` to their spec or test helper.

2. Add `Dotenv.reload` which gets called before initialization. This would track which variables were initially set by dotenv, and reread the configs. This adds a lot of flexibility, but at the cost of some complexity and could lead to unexpected behavior where `config/application.rb` and initializes are loaded with different configurations.

3. Discourage use of `ENV` variables in `config/application.rb` and wait until initialization to load dotenv. This was the original behavior, but is annoyingly inconsistent with dotenv's goal of being an unobtrusive bridge for environment variables.

~~Personally, I'm leaning toward option 1. It replaces complexity with explicit action.~~ Edit: See comment below.

**Comment by BM5k** [comment]
Still seeing this with dotenv-rails & dotenv 2.0.1. Specifically, `rake spec` is picking up config from `.env.development` and not `.env.test`.

Removing dotenv-rails and just using dotenv 2.0.1 by manually calling Dotenv.load in spec_helper doesn’t load `.env.development` or `.env.test`.

**Comment by dideler** [comment]
FYI this issue only occurs for me on my Rails project when I use `dotenv-rails` and `Dotenv::Railtie.load` when running rake. Does not occur when using `dotenv` with `Dotenv.load`.

**Comment by nickgnd** [comment]
As already @dideler said, I solved using `dotenv` gem instead of `dotenv-rails`.

Simply load the environment in `application.rb` and override where you need it (ex. `test_helper.rb`:

```ruby
# config/application.rb
# ...
Bundler.require(*Rails.groups)

# Load env variables
require 'dotenv'
Dotenv.load ".env.local", ".env.#{Rails.env}"

# ...
```

```ruby
# test/test_helper.rb
ENV['RAILS_ENV'] ||= 'test'

require 'dotenv'
Dotenv.overload ".env.#{Rails.env}"

# ...
```

and for tasks which address test environment

```ruby
# force test environment
ENV['RAILS_ENV'] = 'test'
require 'dotenv'
Dotenv.overload ".env.#{Rails.env}"

namespace :test do

  desc "Console in test environment"
  task :console do
    system("bin/rails c")
  end
end
```

tested with:
- ruby 2.3.0
- rails 5.0.0
- dotenv 2.1.1
