### ISSUE TITLE
Not specifying required ruby version on Gemfile causes my bundler with ruby 2.5.x pull dotenv 2.8.0

### ISSUE THREAD

**Issue by 0b5vr** [bkeepers/dotenv#457]
### Steps to reproduce

I was trying to use my old project, install Ruby 2.5.x which the project specifies, install and update dependencies (includes dotenv) using bundler, and encountered this error:

```
SyntaxError: /<MASKED>/dotenv-2.8.0/lib/dotenv/parser.rb:87: syntax error, unexpected ']'
      !line.split[1..].all? { |var| @hash.member?(v...
                     ^
```

It seems dotenv 2.8.0 uses a syntax that Ruby 2.5.x does not understand and it's obvious since the drop of Ruby 2.5.x is written on the changelog: https://github.com/bkeepers/dotenv/releases/tag/v2.8.0

However, the Gemfile of this project does not specify the required ruby version.
It would be nice if it specify the supported ruby version.

Since I rarely do Ruby usually, I have very low confidence about this report.

### Expected behavior

bundler does not install 2.8.0 on my Ruby 2.5.x environment, or emit an appropriate warning or error?

### Actual behavior

2.8.0 was installed in my environment and encountered the error above.

### System configuration

**dotenv version**:

2.8.0

**Rails version**:

---

**Ruby version**:

2.5.3

**Comment by paul-c-hanson** [comment]
We are encountering the same issue on a project for the NHS in the UK. We are pinned to an older version of Ruby at the moment, and the dotenv update has caused an issue in our packaging process. Is there a way to pin the version of dotenv to 2.7.x if the change to the gem file will take some time?

**Comment by tevvi** [comment]
The same issue for ruby 2.5.8. Fixed by:
```ruby
gem 'dotenv-rails', '< 2.8'
```

**Comment by bkeepers** [comment]
I release 2.8.1 that adds support for 2.5 and 2.6. Y'all really should upgrade to a supported version of Ruby.

**Comment by jeff-hiner** [comment]
>Y'all really should upgrade to a supported version of Ruby.

Tell that to the maintainers of CentOS/RHEL 8. I wouldn't care either as I don't directly use Ruby, but my CI system targets RHEL for one build, and we use fpm which depends on dotenv.

I don't think anyone is arguing that you can't or shouldn't drop support for EOL'd Ruby versions, but if you're going to do so the reasonable and polite thing to do is specify a minimum Ruby version in the manifest so as not to break a bunch of folks' builds.

**Comment by natematykiewicz** [comment]
I said basically the same thing here:
https://github.com/bkeepers/dotenv/commit/d7c91354736d97e50618021cbb725ca2dd645976#commitcomment-79569950

**Comment by 0b5vr** [comment]
Thank you for the support, while that was not an intended way to close this issue as others mentioned here.
