### ISSUE TITLE
README should explicitly call out the gem needed is `dotenv-rails`

### ISSUE THREAD

**Issue by myxoh** [bkeepers/dotenv#478]
### Steps to reproduce
README currently starts by talking about the `dotenv` gem:

```
Installation
Add this line to the top of your application's Gemfile and run bundle install:

gem 'dotenv', groups: [:development, :test]
```

And later when talking about Rails
### Rails
Dotenv will automatically load when your Rails app boots. See [Customizing Rails](https://github.com/bkeepers/dotenv#customizing-rails) to change which files are loaded and when.

In no way is it making it clear that the bundle should refer the other gem (which is not mentioned in the readme at all) `dotenv-rails`

Minor change but, unless I'm missing something, would save dumbos like me a few minutes 😅

**Comment by bkeepers** [comment]
@myxoh the README in `main` is for 3.0, which is currently released as beta (#476) which removes the need to install `dotenv-rails` separately. Select the tag for the version you are using to view the relevant README.

**Comment by jmlacroix** [comment]
Glad I found this! I just spent an hour trying to figure out why dotenv didn't load my .env vars.

I think having a temporary note highlighting the name change / version required in the README could be useful to other people too.

**Comment by raldred** [comment]
Same, scratching my head why dotenv not working fresh rails 7 app.

**Comment by bkeepers** [comment]
3.0 is officially out.
