### ISSUE TITLE
Issue with Kamal secrets and ENV vars in dotenv 3.1.5

### ISSUE THREAD

**Issue by ehutzelman** [bkeepers/dotenv#518]
Not sure if this is an issue on the kamal side and how it integrates with dotenv, but it works as expected with dotenv 3.1.4.

### Steps to reproduce

```bash
# .env
AMAZON_KEY_ID=blahblah

# .kamal/secrets
NOT_FETCHED_FROM_ENV=working
AMAZON_KEY_ID=$AMAZON_KEY_ID
````

**Using dotenv 3.1.4**

```bash
> bundle exec dotenv -v
dotenv 3.1.4

> bundle exec dotenv kamal secrets print
NOT_FETCHED_FROM_ENV=working
AMAZON_KEY_ID=blahblah
```

**Using dotenv 3.1.5**

```bash
> bundle exec dotenv -v
dotenv 3.1.5

> bundle exec dotenv kamal secrets print
NOT_FETCHED_FROM_ENV=working
```

When using 3.1.5, the secrets based on ENV vars are missing from output.

### Expected behavior
All secrets should be returned.

### Actual behavior
Only the secrets not fetched from ENV are returned.

### System configuration
**dotenv version**: 3.1.5

**Rails version**: 8.0.0.1

**Kamal version**: 2.3.0

**Ruby version**: 3.3.6

**Comment by kobaltz** [comment]
This was quite the journey in trying to find out the root issue. ❤️ Good discovery!

**Comment by marciotoshio** [comment]
Faced the same issue will crosslink the alert I left in Kamal repo here https://github.com/basecamp/kamal/issues/1294

**Comment by djmb** [comment]
@bkeepers - this is a Kamal issue, not a dotenv one, so you can close this. I'll look at fixing it now.

**Comment by djmb** [comment]
Oh I take that back, I think it is a regression in Dotenv.

If you called `Dotenv.parse`, in 3.1.4 it will return values that are already in the environment, in 3.1.5 they are now ignored - see https://github.com/bkeepers/dotenv/blob/962641232d379472af77908dfed3f2f0a5c234dc/lib/dotenv/parser.rb#L75.

Maybe this change is desired behaviour so `Dotenv.parse` tells you what would actually be added by `Dotenv.load`? 

Either way I think I can fix it in Kamal by calling `Dotenv.parse(file, overwrite: true)`.

**Comment by frenkel** [comment]
@bkeepers thank you!
