### ISSUE TITLE
Newlines are removed in quoted strings

### ISSUE THREAD

**Issue by andrewts129** [bkeepers/dotenv#522]
### Steps to reproduce

Using an `.env` file that has quoted strings with repeated newlines in it:

```sh
# .env
MY_KEY="-----BEGIN SOME KEY BLOCK-----

aaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbb


ccccccccccccccccccc
"
```

### Expected behavior

The command `bundle exec dotenv ruby -e "puts ENV['MY_KEY']"` should print out the MY_KEY variable as given:

```
-----BEGIN SOME KEY BLOCK-----

aaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbb


fdfdfdd
```

### Actual behavior

On `main` / v3.1.6, it instead prints the variable with all the repeated newlines removed:

```
-----BEGIN SOME KEY BLOCK-----
aaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbb
fdfdfdd
```

### System configuration
**dotenv version**: 3.1.6

**Rails version**: n/a

**Ruby version**: 3.1.5

**Comment by andrewts129** [comment]
I ran a git bisect - it looks like the change in behavior started with 25bc9d63c5db4218e7f917fd75cf2cc07efd8cbb

**Comment by bkeepers** [comment]
@andrewts129 thanks for the report. Sorry about that. v3.1.7 is out now with a fix.

**Comment by andrewts129** [comment]
Awesome! Thanks for getting on that so quickly!
