### ISSUE TITLE
Using dotenv to set RAILS_ENV?

### ISSUE THREAD

**Issue by bloudermilk** [bkeepers/dotenv#54]
I'm attempting to use dotenv to control my `RAILS_ENV` variable on our staging environment but when I run any command ActiveRecord complains about no adapter being specified. My `database.yml` contains an entry for our `staging` environment and when I change it to `development` rails boots up juts fine. Can dotenv be used to set `RAILS_ENV`?

**Comment by chiubaka** [comment]
This might be obvious to some people, but any chance documentation about this could get moved up to the README?

I suspected something was special about RAILS_ENV, but being able to search for that string in the README would have saved me an hour of troubleshooting.
