### ISSUE TITLE
Encouraging the committing of .env is a violation of twelve-factor

### ISSUE THREAD

**Issue by binaryphile** [bkeepers/dotenv#67]
To be admittedly nitpicky, the 12f doc at your pointer raises the following (valid) point, emphasis mine:

>Another approach to config is the use of config files which are not checked into revision control, such as `config/database.yml` in Rails. This is a huge improvement over using constants which are checked into the code repo, but still has weaknesses: _it’s easy to mistakenly check in a config file to the repo_;

Later it reiterates:

>Env vars are easy to change between deploys without changing any code; unlike config files, _there is little chance of them being checked into the code repo accidentally_;

I have to say, I agree here.  As long as you're storing sensitive configuration such as secret keys or database passwords in this file, it shouldn't be under version control.  However, you obviously have a good point that _not_ providing sensible defaults gives developers an unnecessary roadblock to getting up and running.

I'm suggesting that the best practice I've seen to deal with this is, like `database.yml` in some projects, to provide a `env.example` or `env.development` or `env.README` (note the absence of the hiding `.` at the beginning) with some sensible development defaults and comments directing the user to copy it to `.env`.  That, along with directions to add `.env` to `.gitignore` seems like the most responsible method of planning for the inevitable mistakes that occur.  Many a time have I accidentally committed sensitive information in a file kept under version control when that file really shouldn't be under vc.

**Comment by bkeepers** [comment]
In https://github.com/bkeepers/dotenv/commit/16802b7e3def2b7d5dccd5656d75780e70de991e I clarified my stance on committing the `.env` file, and in 2.0 (https://github.com/bkeepers/dotenv/pull/160), a `.env.local` file will be also loaded.

I would be happy to entertain an PR with changes to the recommendation in the README, but this is how I handle it on the applications that I maintain.

**Comment by chrisnicola** [comment]
One problem I'm running into with this is there is a completely different philosophy here vs. NPM dotenv and dotenv safe projects. I think the [dotenv-safe](https://github.com/rolodato/dotenv-safe) project has the right idea here.

Commit an example file, it could have default dev values in it and blank values to be filled in, and then locally you can copy it over to .env. It will then report an error for any missing values that are in .env.example to the user so they know exactly why things aren't working.
