### ISSUE TITLE
env values not used by "rails dbconsole"

### ISSUE THREAD

**Issue by odigity** [bkeepers/dotenv#74]
First off, thanks for dotenv -- a simple and effective solution to a universal problem.

I've got the following:
- a fresh Rails 4.0 app
- dotenv
- a .env file in repo root
- postgres
- a database.yml that uses ERB to supply username/password from environment variables, which are loaded by dotenv from .env

Everything works fine:
- rails server brings up the server, which successfully connects to the db
- rake db:\* commands work correctly

The only exception is "rails dbconsole".  It doesn't seem to inherit the env vars, and instead tries to connect via my local username.  When I prepend the value manually, it does pick it up:

$ POSTGRESQL_USERNAME=whatever rails dbconsole

I don't know much about Rails internals.  I would assume that "rails dbconsole" would have the same bootstrapping/gem-invoking process as "rails server", but either it's failing to load dotenv, or it doesn't consult database.yml for creds.

I believe the command merely invokes the 'psql' command-line client on my behalf, but it should still be supplying values from database.yml, shouldn't it?

**Comment by indirect** [comment]
@jhirbour you need to set RAILS_ROOT for Rails to know where the root is, so dotenv can find the .env file.

**Comment by jhirbour** [comment]
Ah ok. I've switched jobs since my last post.. I'll send this to my former co-workers.

**Comment by Willibaur** [comment]
I'm not sure if this the same issue posted before, but I if you have your tokens on `.env` file in your project and on your `.bash_profie` as well, dotenv reads always your bash ones first instead of going directly to your .env

**Comment by bkeepers** [comment]
> I'm not sure if this the same issue posted before, but I if you have your tokens on `.env` file in your project and on your `.bash_profie` as well, dotenv reads always your bash ones first instead of going directly to your .env

This is by design. The deployment environment always knows more than the application, so environment variables that are already set will take precedence over `.env`. You can manually call `Dotenv.overload` in your application if you do not want that behavior.
